### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by benedictleejh** [file-icons/atom#492]
Steps to reproduce:

1. Open Atom

**Atom Version**: 1.12.8
**Electron Version**: 1.3.13
**System**: Mac OS X 10.10.5
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v2.0.5

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At ~/.atom/packages/file-icons/lib/ui.js:127

TypeError: Cannot read property '0' of null
    at UI.getThemeColour (~/.atom/packages/file-icons/lib/ui.js:127:17)
    at UI.checkMotif (~/.atom/packages/file-icons/lib/ui.js:134:23)
    at Immediate._ (~/.atom/packages/file-icons/lib/ui.js:17:27)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
  2x -0:00.7.0 blur (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "metrics",
      "markdown-preview",
      "language-gfm",
      "language-gitignore",
      "language-dots",
      "tree-view"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "atom-material-ui",
      "ocaml-indent"
    ],
    "projectHome": "~/projects",
    "telemetryConsent": "no",
    "themes": [
      "yosemate-ui",
      "gl-light-syntax"
    ]
  },
  "file-icons": {}
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v2.7.1 (active)
atom-beautify, v0.29.16 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.8 (inactive)
build, v0.67.0 (active)
build-gradle, v0.6.0 (active)
build-gulp, v0.11.0 (active)
build-make, v0.13.0 (active)
build-rake, v0.1.1 (active)
busy, v0.7.0 (active)
copy-as-rtf, v0.9.3 (inactive)
elm-snippets, v0.1.0 (active)
file-icons, v2.0.5 (active)
gitignore-snippets, v0.2.5 (inactive)
gl-light-syntax, v2.2.0 (active)
goto, v1.8.2 (inactive)
highlight-selected, v0.11.2 (active)
kuali-light-syntax, v1.1.0 (inactive)
language-asciidoc, v1.6.2 (inactive)
language-elm, v1.5.0 (inactive)
language-gradle, v0.0.3 (inactive)
language-groovy, v0.6.0 (inactive)
language-idris, v0.4.5 (inactive)
language-ignore, v1.5.2 (inactive)
language-latex, v1.0.0 (inactive)
language-ocaml, v1.1.2 (inactive)
language-pfm, v0.82.0 (inactive)
language-slim, v0.5.0 (inactive)
latextools, v0.8.5 (active)
linter, v1.11.18 (active)
linter-elm-make, v0.18.1 (active)
markdown-preview-plus, v2.4.0 (active)
markdown-scroll-sync, v2.1.2 (active)
metro-ui, v2.2.2 (inactive)
minimap, v4.25.7 (active)
minimap-highlight-selected, v4.4.0 (active)
move-panes, v0.2.0 (inactive)
nuclide, v0.194.0 (active)
ocaml-indent, v0.5.0 (inactive)
open-recent, v5.0.0 (active)
pdf-view, v0.54.0 (active)
pigments, v0.37.0 (active)
proton-framer, v0.11.0 (inactive)
proton-light, v0.2.0 (inactive)
Repl, v0.5.0 (active)
soda-light-ui, v0.2.0 (inactive)
terminal-plus, v0.14.5 (active)
tool-bar, v1.0.1 (active)
tool-bar-main, v0.0.10 (active)
unity-ui, v2.1.8 (inactive)
yosemate-ui, v0.7.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
Hrm, does [clearing the cache](https://github.com/file-icons/atom#troubleshooting) help?

**Comment by benedictleejh** [comment]
Just tried that, and it doesn't help. Also, the error shows up on each new window opened.

It also seems to be OS X specific, as I'm not getting the error on Linux. I don't have a Windows machine to test though.

**Comment by Alhadis** [comment]
Oh! Wait, I know what it is. Hang on.

**Comment by Alhadis** [comment]
Please let me know if you're still witnessing this after installing the latest patch. :-)

Sorry for the mess.
