### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by FlappyHeart** [file-icons/atom#493]
[Enter steps to reproduce below:]

1. Push cmd+T on Mac
2. Then popup this error

**Atom Version**: 1.12.8
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.6

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/alfred/.atom/packages/file-icons/lib/filesystem/file.js:276

TypeError: Cannot read property 'indexOf' of undefined
    at File.watchRepo (/Users/alfred/.atom/packages/file-icons/lib/filesystem/file.js:276:45)
    at new File (/Users/alfred/.atom/packages/file-icons/lib/filesystem/file.js:23:8)
    at FileSystem.get (/Users/alfred/.atom/packages/file-icons/lib/filesystem/filesystem.js:84:7)
    at FuzzyFinder.trackEntry (/Users/alfred/.atom/packages/file-icons/lib/consumers/consumer.js:157:27)
    at timeouts.set._ (/Users/alfred/.atom/packages/file-icons/lib/consumers/fuzzy-finder.js:155:10)
```

### Commands

```
     -0:07.4.0 core:close (div.panels-item)
     -0:05.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:02.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "nav-panel-plus"
    ],
    "packagesWithKeymapsDisabled": [
      "file-icons"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "file-icons": {
    "onChanges": true,
    "strategies": {}
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.5 (inactive)
atom-autocomplete-php, v0.20.2 (active)
atom-beautify, v0.29.16 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-jinja2, v0.6.0 (active)
atom-sync, v0.7.3 (active)
autoclose-html, v0.23.0 (active)
autocomplete-php, v0.3.7 (active)
autocomplete-project-paths, v2.2.0 (active)
color-picker, v2.2.3 (active)
emmet, v2.4.3 (active)
file-header, v1.13.0 (active)
file-icons, v2.0.6 (active)
git-plus, v7.0.4 (active)
highlight-line, v0.11.2 (active)
highlight-selected, v0.11.2 (active)
jquery-snippets, v11.0.0 (active)
language-smarty, v1.7.0 (active)
linter, v1.11.18 (active)
monokai, v0.18.0 (active)
nav-panel-plus, v0.1.3 (inactive)
pigments, v0.37.0 (active)
react, v0.16.2 (active)
Remote-FTP, v0.9.4 (active)
remote-sync, v4.1.5 (active)
sequential-number, v0.4.0 (inactive)
sync-settings, v0.8.1 (active)
todo-show, vundefined (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
Does restarting Atom help?

**Comment by FlappyHeart** [comment]
No, I had restarted Atom many times.

**Comment by Alhadis** [comment]
Does [clearing the cache](https://github.com/file-icons/atom#troubleshooting) help?

**Comment by FlappyHeart** [comment]
No, I had tried too.

**Comment by Alhadis** [comment]
No. If I could, I would be working on solving it...

What projects do you currently have open when this happens?

**Comment by Alhadis** [comment]
Never mind. 9b6d3ce should solve it.

**Comment by Alhadis** [comment]
Please let me know if you're still experiencing this, okay? :)

**Comment by FlappyHeart** [comment]
sorry I am busy with my work for several hours. I have installed the older version @1.7.25


发自网易邮箱大师专业版
On 01/04/2017 18:01, John Gardner wrote:

Please let me know if you're still experiencing this, okay? :)

**Comment by FlappyHeart** [comment]
I found the new version was published and I update my file-icons to the newest version. Then this issue was fixed. Thanks a lot!

**Comment by Alhadis** [comment]
好消息！ 对不起，乱。:(
