### ISSUE TITLE
Uncaught TypeError: document.styleSheets[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by Eblonko** [file-icons/atom#503]
1. update package
2. restart atom

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.7

### Stack Trace

Uncaught TypeError: document.styleSheets[Symbol.iterator] is not a function

```
At /home/vitaly/.atom/packages/file-icons/lib/ui.js:113

TypeError: document.styleSheets[Symbol.iterator] is not a function
    at UI.getStyleElement (/home/vitaly/.atom/packages/file-icons/lib/ui.js:113:33)
    at UI.getThemeColour (/home/vitaly/.atom/packages/file-icons/lib/ui.js:123:27)
    at UI.checkMotif (/home/vitaly/.atom/packages/file-icons/lib/ui.js:136:23)
    at Immediate._ [as _onImmediate] (/home/vitaly/.atom/packages/file-icons/lib/ui.js:17:27)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  },
  "file-icons": {
    "coloured": false,
    "onChanges": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
atom-easy-jsdoc, v4.8.0 (inactive)
atom-ternjs, v0.16.1 (inactive)
atomic-chrome, v0.3.0 (active)
autocomplete-modules, v1.6.7 (active)
chester-atom-syntax, v0.1.1 (active)
file-icons, v2.0.7 (active)
git-plus, v7.0.4 (active)
language-pascal, v0.20.1 (inactive)
language-vue, v0.21.0 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
node-snippets, v0.0.7 (active)
python-indent, v1.0.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Eblonko** [comment]
just updated to atom 1.12.9 and there's no error message

**Comment by maximumdata** [comment]
I am getting this error every time atom is launched, or the window is refreshed. The error contains a link to this closed issue. 

Atom 1.11.2, file-icons 2.0.8
