### ISSUE TITLE
Uncaught TypeError: Cannot read property 'roots' of null

### ISSUE THREAD

**Issue by wolfkingchuang** [file-icons/atom#506]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'roots' of null

```
At /Users/hechuang/.atom/packages/file-icons/lib/consumers/tree-view.js:119

TypeError: Cannot read property 'roots' of null
  at TreeView.rebuild (/Users/hechuang/.atom/packages/file-icons/lib/consumers/tree-view.js:119:33)
  at disposables.add.atom.project.onDidChangePaths._ (/Users/hechuang/.atom/packages/file-icons/lib/consumers/tree-view.js:43:45)
  at Function.module.exports.Emitter.simpleDispatch (/Users/hechuang/Develop/tools/Atom/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Users/hechuang/Develop/tools/Atom/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at Project.module.exports.Project.addPath (/Users/hechuang/Develop/tools/Atom/Atom.app/Contents/Resources/app.asar/src/project.js:270:29)
  at /Users/hechuang/Develop/tools/Atom/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:985:40
  at EventEmitter.<anonymous> (/Users/hechuang/Develop/tools/Atom/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:27:16)
  at emitTwo (events.js:106:13)
  at EventEmitter.emit (events.js:191:7)

```

### Commands

```
     -0:58.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:09.0 nuclide-file-tree:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:09.0 nuclide-file-tree:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:08.3.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited"
  },
  "file-icons": {
    "strategies": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
atom-typescript, v10.1.13 (active)
file-icons, v2.0.7 (active)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.48.5 (active)
language-graphql, v0.8.0 (active)
language-ini, v1.17.0 (active)
language-lua, v0.9.11 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
linter, v1.11.18 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.7 (active)
nuclide, v0.195.0 (active)
nuclide-format-js, v0.0.36 (inactive)
platformio-ide-terminal, v2.2.2 (active)
set-syntax, v0.3.2 (active)
sort-lines, v0.14.0 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
>  -0:09.0 nuclide-file-tree:reveal-active-file

@wolfkingchuang Are you using Nuclide? Because there's currently no support for that yet. See facebook/nuclide#951.
