### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by vintagesucks** [file-icons/atom#510]
**Steps to reproduce:**

1. Open Atom
2. Remove current project folder
3. Add C:\ as project folder (error is thrown)
4. Exit Atom
5. Repeat

**Atom**: 1.14.0-beta0 x64
**Electron**: 1.3.13
**OS**: W10
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.0.8

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At C:\Users\nikol\.atom\packages\file-icons\lib\filesystem\filesystem.js:147

TypeError: Cannot read property 'path' of undefined
    at FileSystem.fixPath (/packages/file-icons/lib/filesystem/filesystem.js:147:14)
    at resource.onDidMove.paths (/packages/file-icons/lib/filesystem/filesystem.js:104:38)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Directory.emit (/packages/file-icons/lib/filesystem/resource.js:111:17)
    at Directory.setPath (/packages/file-icons/lib/filesystem/resource.js:252:9)
    at FileSystem.get (/packages/file-icons/lib/filesystem/filesystem.js:80:15)
    at /packages/file-icons/lib/consumers/tree-entry.js:23:30)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:132:25)
    at TreeView.rebuild (/packages/file-icons/lib/consumers/tree-view.js:123:9)
    at disposables.add.atom.project.onDidChangePaths._ (/packages/file-icons/lib/consumers/tree-view.js:43:45)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/app.asar/src/project.js:270:29)
    at /app.asar/src/atom-environment.js:1007:40
    at /app.asar/src/application-delegate.js:27:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -0:19.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-firewatch-syntax.theme-one-dark-ui)
     -0:15 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -0:11.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.29.16 
autocomplete-php 0.3.7 
file-icons 2.0.8 
firewatch-syntax 1.0.1 
language-generic-config 1.3.0 
linter 1.11.18 
linter-eslint 8.0.0 
linter-php 1.3.1 
linter-stylelint 3.7.0 
php-cs-fixer 4.1.0 
```

**Comment by Alhadis** [comment]
Right, one massive VirtualBox download later...

**Atom 1.13**  
- No error
- `C:\\` has no name when added as project folder

**Atom 1.14-beta**
- Throws error
- `C:\\` has name of `.` when added as project folder

Will attempt to fix, but man, what the hell? 😀

**Comment by Skywalker13** [comment]
FYI: I've the same error and I'm under Linux. Seems not always reproducible and I'm not in the root..

**Comment by Alhadis** [comment]
Fixed by 09327d0483a85550c2ea015342423d55f428e5f5.

**Comment by idesignstuff** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.9


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At C:\Users\ritchcd\.atom\packages\file-icons\lib\filesystem\filesystem.js:147

TypeError: Cannot read property 'path' of undefined
    at FileSystem.fixPath (C:\Users\ritchcd\.atom\packages\file-icons\lib\filesystem\filesystem.js:147:14)
    at resource.onDidMove.paths (C:\Users\ritchcd\.atom\packages\file-icons\lib\filesystem\filesystem.js:104:38)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at File.emit (C:\Users\ritchcd\.atom\packages\file-icons\lib\filesystem\resource.js:111:17)
    at File.setPath (C:\Users\ritchcd\.atom\packages\file-icons\lib\filesystem\resource.js:252:9)
    at FileSystem.get (C:\Users\ritchcd\.atom\packages\file-icons\lib\filesystem\filesystem.js:80:15)
    at Object.iconClassForPath (C:\Users\ritchcd\.atom\packages\file-icons\lib\service\icon-service.js:37:29)
    at tree-view-file.module.exports.FileView.initialize (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\file-view.js:35:42)
    at tree-view-directory.DirectoryView.createViewForEntry (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory-view.js:134:12)
    at C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory-view.js:105:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:125:28)
    at Directory.module.exports.Directory.reload (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory.js:370:29)
    at Directory.module.exports.Directory.expand (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory.js:383:12)
    at tree-view-directory.DirectoryView.expand (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory-view.js:179:24)
    at tree-view-directory.DirectoryView.toggleExpansion (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory-view.js:166:21)
    at TreeView.module.exports.TreeView.entryClicked (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:472:15)
    at tree-view-directory.<anonymous> (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:190:26)
    at space-pen-div.dispatch (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\ritchcd\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -2:27.4.0 platformio-ide:target:build (input.hidden-input)
     -2:27.4.0 platformio-ide:target:build-C:\Users\ritchcd\Documents\pio\TeamPulse (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".pioenvs",
      ".piolibdeps",
      ".clang_complete",
      ".gcc-flags.json"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.10.0 (active)
build, v0.67.0 (active)
busy, v0.7.0 (active)
file-icons, v2.0.9 (active)
language-ini, v1.17.0 (active)
linter, v1.11.21 (active)
linter-gcc, v0.6.15 (active)
minimap, v4.26.6 (active)
platformio-ide, v1.7.1 (active)
platformio-ide-terminal, v2.2.2 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
@idesignstuff You're using an outdated version of this package, and commenting on an issue that's been fixed in more recent versions. Please upgrade.

**Comment by idesignstuff** [comment]
OK thanks. I think PlatformIO hasn't pointed to the latest version yet.



Christian
