### ISSUE TITLE
Uncaught TypeError: document.styleSheets[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by elpagano** [file-icons/atom#523]
![screenshot_20170117_103511](https://cloud.githubusercontent.com/assets/6748514/22022547/2a147cbe-dccb-11e6-82eb-b6813f7e7739.png)
The error was thrown from the file-icons package. 
this happens every time y start atom but the package its works perfectly

**Comment by Alhadis** [comment]
Está siendo fijo. Duplicado de #519.

**Comment by salcedogeiner** [comment]
TypeError: document.styleSheets[Symbol.iterator] is not a function
    at UI.getStyleElement (/.atom/packages/file-icons/lib/ui.js:151:33)
    at UI.getThemeColour (/.atom/packages/file-icons/lib/ui.js:161:27)
    at UI.checkMotif (/.atom/packages/file-icons/lib/ui.js:176:23)
    at Immediate.setImmediate (/.atom/packages/file-icons/lib/ui.js:24:29)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

### Commands

```
     -0:10.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-material-syntax.theme-one-dark-ui)
```

**Comment by Alhadis** [comment]
@salcedogeiner Run this in devtools, please:

~~~js
console.log(document);
console.log(document.constructor);
console.log(document.styleSheets);
console.log(document.styleSheets.constructor);
~~~

Show me what it outputs.

**Comment by hurtauda** [comment]
I got the same error so here are the outputs :
```
TypeError: document.styleSheets[Symbol.iterator] is not a function
    at UI.getStyleElement (/home/ahurtaud/.atom/packages/file-icons/lib/ui.js:151:33)
    at UI.getThemeColour (/home/ahurtaud/.atom/packages/file-icons/lib/ui.js:161:27)
    at UI.checkMotif (/home/ahurtaud/.atom/packages/file-icons/lib/ui.js:176:23)
    at Immediate.setImmediate (/home/ahurtaud/.atom/packages/file-icons/lib/ui.js:24:29)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```
`console.log(document);`
![image](https://cloud.githubusercontent.com/assets/4448200/22549374/4a40ff76-e94b-11e6-8c4c-20e6e986f5ac.png)

`console.log(document.constructor);`
![image](https://cloud.githubusercontent.com/assets/4448200/22549352/3ddcb4dc-e94b-11e6-9606-b86c62659f1a.png)

`console.log(document.styleSheets);`
![image](https://cloud.githubusercontent.com/assets/4448200/22549404/6ab9e5b0-e94b-11e6-8ff9-f36d4e9eca84.png)
[ ... ]
![image](https://cloud.githubusercontent.com/assets/4448200/22549504/f0eed276-e94b-11e6-975d-11f48cf9cd0e.png)

`console.log(document.styleSheets.constructor);`
![image](https://cloud.githubusercontent.com/assets/4448200/22549420/7e47e622-e94b-11e6-9fab-478975c99b96.png)

I hope that helps

**Comment by DannyLeiton** [comment]
So? What's the solution for this?

**Comment by Alhadis** [comment]
If people would stop commenting on **duplicated issues** and confine discussion to the [appropriate issue](https://github.com/file-icons/atom/issues/519#issuecomment-276857668), they'd notice this issue [has already been solved](https://github.com/file-icons/atom/issues/519#issuecomment-276857668).

That's it. From now on, duplicate issues are being locked. I can't keep giving the same update to three different mobs of people at entirely asynchronous intervals.
