### ISSUE TITLE
No SVN support

### ISSUE THREAD

**Issue by zhudock** [file-icons/atom#537]
[Enter steps to reproduce below:]

1. With Project Viewer plugin installed, click on a project in the sidebar

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.14

### Stack Trace

Uncaught TypeError: repo.isWorkingDirectory is not a function

```
At C:\Users\zrh535\.atom\packages\file-icons\lib\filesystem\directory.js:26

TypeError: repo.isWorkingDirectory is not a function
	at new Directory (C:\Users\zrh535\.atom\packages\file-icons\lib\filesystem\directory.js:26:12)
	at FileSystem.get (C:\Users\zrh535\.atom\packages\file-icons\lib\filesystem\filesystem.js:104:7)
	at new TreeEntry (C:\Users\zrh535\.atom\packages\file-icons\lib\consumers\tree-entry.js:23:30)
	at TreeView.track (C:\Users\zrh535\.atom\packages\file-icons\lib\consumers\tree-view.js:72:25)
	at TreeView.rebuild (C:\Users\zrh535\.atom\packages\file-icons\lib\consumers\tree-view.js:63:9)
	at disposables.add.atom.project.onDidChangePaths (C:\Users\zrh535\.atom\packages\file-icons\lib\consumers\tree-view.js:47:45)
	at Function.module.exports.Emitter.simpleDispatch (C:\Users\zrh535\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
	at Emitter.module.exports.Emitter.emit (C:\Users\zrh535\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
	at Project.module.exports.Project.setPaths (C:\Users\zrh535\AppData\Local\atom\app-1.13.1\resources\app.asar\src\project.js:233:27)
	at Project.module.exports.Project.deserialize (C:\Users\zrh535\AppData\Local\atom\app-1.13.1\resources\app.asar\src\project.js:116:19)
	at Object.projectDeserialization (C:\Users\zrh535\.atom\packages\project-viewer\src\states.js:11:22)
	at pv-list-item.clickListener (C:\Users\zrh535\.atom\packages\project-viewer\src\list-item-component.js:73:17)
```

### Commands

```
  3x -8:21.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:21.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -8:17.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:04.2.0 project-viewer:create-group-item (ul.list-tree.has-collapsable-children.padded)
     -5:45.9.0 project-viewer:create-project-item (li#pv_1f76e1ca-7d46-4857-956a-419dc5d40338.list-nested-item.collapsed)
 19x -5:41.4.0 core:backspace (input.hidden-input)
     -1:55.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:26.9.0 command-palette:toggle (input.hidden-input)
     -0:19.6.0 file-icons:clear-cache (input.hidden-input)
  2x -0:14.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
	"core": {
		"telemetryConsent": "no"
	}
}
```

### Packages

```sh
# Enabled themes
one-dark-ui           1.8.2
one-dark-syntax       1.6.0

# Consumer packages
archive-view          0.62.0
find-and-replace,     0.204.5  (Inactive)
fuzzy-finder          1.4.0
tabs                  0.103.1
tree-view             0.211.1

# Active (Core excluded)
atom-alignment        0.12.1
atom-beautify         0.29.17  (Inactive)
autocomplete-oracle   0.4.0
busy                  0.7.0
console-panel         0.2.1
file-icons            2.0.14
git-plus              7.2.0
language-batch        0.3.3
language-dots         0.0.4
language-oracle       1.6.2
language-sqr          0.8.0
language-vbscript     0.7.0
line-ending-converter 1.3.2
linter                1.11.21
minimap               4.26.8
pigments              0.39.0
project-view          0.6.1
project-viewer        0.3.43
save-session          0.15.7
svn                   0.0.13
symbols-tree-view     0.13.2
synced-sidebar        0.4.3
tabasco               0.5.0
tabs-to-spaces        1.0.3
tortoise-svn          0.5.0  (Inactive)
```

**Comment by Alhadis** [comment]
Could you run this in your dev-console and show me what it outputs, please?

~~~js
console.log(atom.project.repositories)
~~~

**Comment by zhudock** [comment]
How much of the output would be helpful? I'm having difficulty getting the [SvnRepository] object to expand.

It seems this exception only happens if the [atom-svn](https://github.com/andischerer/atom-svn) plugin is enabled. If I disable the plugin, I lose changed file highlighting from the treeview, but the exception stops as well.

**Comment by Alhadis** [comment]
I wish SVN would die. Seriously.

Leave it with me. I can tell what's going wrong.
