### ISSUE TITLE
No Mercurial support

### ISSUE THREAD

**Issue by chiselko6** [file-icons/atom#540]
**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.14

### Stack Trace

Uncaught TypeError: repo.isWorkingDirectory is not a function

```
At /home/nb-108a/.atom/packages/file-icons/lib/filesystem/directory.js:26

TypeError: repo.isWorkingDirectory is not a function
	at new Directory (/home/nb-108a/.atom/packages/file-icons/lib/filesystem/directory.js:26:12)
	at FileSystem.get (/home/nb-108a/.atom/packages/file-icons/lib/filesystem/filesystem.js:104:7)
	at new TreeEntry (/home/nb-108a/.atom/packages/file-icons/lib/consumers/tree-entry.js:23:30)
	at TreeView.track (/home/nb-108a/.atom/packages/file-icons/lib/consumers/tree-view.js:72:25)
	at TreeView.rebuild (/home/nb-108a/.atom/packages/file-icons/lib/consumers/tree-view.js:63:9)
	at disposables.add.atom.project.onDidChangePaths (/home/nb-108a/.atom/packages/file-icons/lib/consumers/tree-view.js:47:45)
	at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
	at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
	at Project.module.exports.Project.addPath (/usr/share/atom/resources/app.asar/src/project.js:270:29)
	at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/usr/share/atom/resources/app.asar/src/atom-environment.js:1191:26)
	at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:236:18)
	at emitThree (events.js:121:20)
	at EventEmitter.emit (events.js:194:7)
```

### Commands

```
       -2:15.3.0 core:confirm (input.hidden-input)
    3x -2:08.8.0 editor:delete-to-beginning-of-word (input.hidden-input)
       -2:07.1.0 core:confirm (input.hidden-input)
       -2:00.0 editor:delete-to-beginning-of-word (input.hidden-input)
       -1:57.9.0 core:backspace (input.hidden-input)
       -1:54.4.0 core:confirm (input.hidden-input)
    5x -1:48.8.0 editor:delete-to-beginning-of-word (input.hidden-input)
       -1:46.8.0 core:confirm (input.hidden-input)
       -1:38.9.0 editor:delete-to-beginning-of-word (input.hidden-input)
       -1:34.4.0 core:confirm (input.hidden-input)
    3x -0:30.8.0 editor:delete-to-beginning-of-word (input.hidden-input)
       -0:26.7.0 core:backspace (input.hidden-input)
       -0:25.9.0 core:confirm (input.hidden-input)
    3x -0:13.4.0 editor:delete-to-beginning-of-word (input.hidden-input)
       -0:04.5.0 application:open-folder (input.hidden-input)
       -0:00.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
	"core": {
		"telemetryConsent": "limited"
	}
}
```

### Packages

```bash
# Enabled themes
one-dark-ui          1.8.2
one-dark-syntax      1.6.0

# User (Core excluded)
atom-beautify        0.29.17 (Inactive)
atom-hg              2.0.11
atom-wrap-in-tag     0.6.0   (Inactive)
autoclose-html       0.23.0
color-picker         2.2.5
emmet                2.4.3
file-icons           2.0.14
highlight-selected   0.12.0
language-logicblox   0.2.1
linter               1.11.21
linter-jshint        3.0.2
minimap              4.26.8
minimap-split-diff   0.3.2
pigments             0.39.0
split-diff           1.1.1  (Inactive)

# Consumer packages
archive-view         0.62.0
find-and-replace     0.204.5 (Inactive)
fuzzy-finder         1.4.0
tabs                 0.103.1
tree-view            0.211.1
```

**Comment by Alhadis** [comment]
@chiselko6 Is this a version-controlled project you're working on? If so, what VCS system is it using?

**Comment by chiselko6** [comment]
@Alhadis yes, we use mercurial.

**Comment by Alhadis** [comment]
Mercurial. Crap, what other VCS systems does Atom support? :|

I'll investigate.

**Comment by Alhadis** [comment]
Fixed, thank you. This will be published later today.

**Comment by chiselko6** [comment]
@Alhadis Thanks a lot!
