### ISSUE TITLE
Uncaught TypeError: this.childProcess.send is not a function

### ISSUE THREAD

**Issue by jarovarga** [file-icons/atom#547]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.0.15

### Stack Trace

Uncaught TypeError: this.childProcess.send is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:117

TypeError: this.childProcess.send is not a function
    at Task.module.exports.Task.send (/app.asar/src/task.js:117:27)
    at Task.module.exports.Task.start (/app.asar/src/task.js:108:12)
    at Function.module.exports.Task.once (/app.asar/src/task.js:21:18)
    at System.sendRequests (/packages/file-icons/lib/filesystem/system.js:88:21)
    at timeoutID._ (/packages/file-icons/lib/filesystem/system.js:51:42)
```

### Commands

```
     -4:37 core:backspace (input.hidden-input)
     -4:36.9.0 editor:consolidate-selections (input.hidden-input)
     -4:36.9.0 atom-minify:close-panel (input.hidden-input)
     -4:36.9.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-minify 0.8.0 
editorconfig 2.2.1 
file-icons 2.0.15 
less-autocompile 1.0.0 
local-history 4.0.1 
php-twig 4.0.0 
sort-lines 0.14.0 
symbols-tree-view 0.13.2 
```

**Comment by Alhadis** [comment]
How often has this happened?

**Comment by Alhadis** [comment]
@jarovarga I'm going to close this, as the stack-trace suggests it's a problem in Atom's core.

If this happens again, please open an issue at [Atom's official repository](https://github.com/atom/atom/issues).
