### ISSUE TITLE
Cannot find module 'micromatch'(Failed to activate the file-icons package) 

### ISSUE THREAD

**Issue by Princeraul** [file-icons/atom#554]
**Atom Version: 1.14.0
System: Microsoft Windows 10 
Thrown From: file-icons package, v2.0.17**

Error: Cannot find module 'micromatch'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (E:\Atom\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (E:\Atom\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (E:\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Princeraul\.atom\packages\atom\lib\service\strategies\linguist-strategy.js:4:20)
    at Module._compile (E:\Atom\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (E:\Atom\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (E:\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at StrategyManager.init (C:\Users\Princeraul\.atom\packages\atom\lib\service\strategy-manager.js:18:4)
    at IconService.init (C:\Users\Princeraul\.atom\packages\atom\lib\service\icon-service.js:15:19)
    at Object.activate (C:\Users\Princeraul\.atom\packages\atom\lib\main.js:22:15)
    at Package.module.exports.Package.activateNow (E:\Atom\resources\app.asar\src\package.js:218:19)
    at E:\Atom\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (E:\Atom\resources\app.asar\src\package.js:96:15)
    at E:\Atom\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (E:\Atom\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (E:\Atom\resources\app.asar\src\package-manager.js:550:34)
    at E:\Atom\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (E:\Atom\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (E:\Atom\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (E:\Atom\resources\app.asar\src\package-manager.js:508:46)
    at E:\Atom\resources\app.asar\src\atom-environment.js:814:28

**Comment by Alhadis** [comment]
Please make sure you've [installed this package correctly](https://github.com/file-icons/atom#installation).

**Comment by Zewkin** [comment]
I can't "install this package correctly" because of damn corporate proxy. I've been googling for two days already - nothing worked, the only option for me is to install file-icons manually (i used [that](http://stackoverflow.com/questions/36582843/how-to-install-atom-packages-offline-or-when-the-atom-package-manager-doesnt-wo) how-to), but now I get that error.

**Comment by Alhadis** [comment]
@Zewkin When Atom runs, it loads user-installed files and preferences from `~/.atom`. Installed packages are loaded from `~/.atom/packages`.

In essence, installing a package is just a matter of extracting a zip file to the right location:

1. Download the [latest version of the package](https://github.com/file-icons/atom/archive/master.zip)
2. Extract its contents to `~/.atom/packages/file-icons`
3. Install the necessary dependencies:
~~~bash
cd ~/.atom/packages/file-icons
apm install .
~~~
4. Restart Atom

Please let me know if that works.
