### ISSUE TITLE
Random Coffeescript file showing up as Appveyor

### ISSUE THREAD

**Issue by 50Wliu** [file-icons/atom#563]
![coffeescript-appveyor](https://cloud.githubusercontent.com/assets/2766036/24123599/8c7870f8-0d96-11e7-8ff8-fe3fc2ba69be.png)

The tab icon when you open it is the Coffeescript brown + the Appveyor icon.  Switching languages does _not_ help.

file-icons@2.0.17

**Comment by Alhadis** [comment]
Right, kick devtools open. Run this:

~~~js
_FileIcons.fs.paths
~~~

Tell me if:
1. Any paths are using backwards delimiters
2. Any entries are keyed with values that *aren't* Directory or File instances
3. If more than one key exists for a path (...somehow)

**Next:**

~~~js
const fubar = _FileIcons.grep("git-repository-spec.coffee");
~~~

Show me the contents of:
- `fubar.icons`
- `fubar.currentIcon`

**Comment by 50Wliu** [comment]
The path for `C:\Users\user\Documents\GitHub\atom\spec\git-repository-spec.coffee` is pointing to uh... `C:/Users/user/Documents/GitHub/atom/appveyor.yml`...

The two properties are undefined.

**Comment by Alhadis** [comment]
2017 and Microsoft still insist on using relics of the DOS-era. Christ, I hate those separators...

Right, that's made the catalyst pretty clear. What I can't understand is how it fell through the dozens of `normalisePath` calls I scattered everywhere to make sure no backwards/weird-Windows paths were used as keys. \*sigh*

Thankfully, stuff like this is about to become easier to debug. Almost finished decoupling the filesystem API... -_-

Guess there's nothing insightful in `_FileIcons.log`?

**Comment by 50Wliu** [comment]
Oh, all my keys were Windows-style.  Their corresponding File was mapped to a Unix-style path though.  Is that worrisome?

![image](https://cloud.githubusercontent.com/assets/2766036/24126796/642a375c-0da6-11e7-927e-f0a33993c859.png)

**Comment by Alhadis** [comment]
Quite the opposite. To make my life simpler and less prickly, I force Windows paths to use POSIX path separators. Every path is meant to be normalised this way before lookup. Obviously something slipped through the gaps somewhere, because those keys aren't meant to be delimited like that.

Is your `process.platform` global set to `"win32"`...?

**Comment by 50Wliu** [comment]
```
process.platform
"win32"
```

**Comment by Alhadis** [comment]
The separator discrepancies are the reason for this schizophrenic mess. If I can plug that, this issue will likely be resolved. Needless to say, this is probably connected to the original issue you filed.

I should also check the latest beta to see if there's anything broken I need to fix... -_-

**Comment by Alhadis** [comment]
BTW, improved path-handling will need to wait for another release. I didn't wanna hold off publishing `v2.0.0`, but I didn't want to rush anything either.

Which overlooks the fact I just spent several hours mud-wrestling both NPM and APM to get these versions published, but yeah.

**Comment by 50Wliu** [comment]
Just updated to 2.1.1 and I :heart: the new test icons though :).

**Comment by Alhadis** [comment]
Glad to hear that, haha. Spent hours designing 'em. :)

It's interesting how difficult icons are to design well... so little room, so many details can get lost so easily...

**Comment by 50Wliu** [comment]
@Alhadis is this maybe the same issue that I'm seeing right now?
![coffee-disguised-as-folder](https://user-images.githubusercontent.com/2766036/30775925-87ca1102-a09d-11e7-8876-78dc4b1e6a5d.png)

**Comment by Alhadis** [comment]
Freshly-cloned? As in, you didn't create new directories or rename files in the `tree-view` after seeing this?

Have you cloned this repo to its current directory before...?

**Comment by 50Wliu** [comment]
> As in, you didn't create new directories or rename files in the tree-view after seeing this?

Nope.

> Have you cloned this repo to its current directory before...?

Maybe a long time ago.  I have not _recently_ cloned this repo.

Here's the full tree: you can see it happening twice.
![csharp-full-tree](https://user-images.githubusercontent.com/2766036/30775979-45b5320a-a09e-11e7-81b3-0f8cd7fc7f7f.png)

**Comment by 50Wliu** [comment]
Introducing: I have no idea what is going on.  This is from a new Atom window (`atom . -n`).
![csharp-new-window](https://user-images.githubusercontent.com/2766036/30775999-922e7538-a09e-11e7-91d3-fca7602dcd85.png)

**Comment by Alhadis** [comment]
Could you show the output of `apm ls -bi`, please? I'm gonna have a look at this from a virtualised Windows environment, since I've been unable to reproduce this on Darwin.

**Comment by 50Wliu** [comment]
This isn't going to be of much help because the majority of the packages are linked, but here you go.
```
atom-ide-ui@0.3.3
autocomplete-css@0.17.3
autocomplete-html@0.8.2
autocomplete-java@1.2.7
autocomplete-python@1.10.3
bracket-matcher@0.88.0
busy-signal@1.4.3
encoding-selector@0.23.6
file-icons@2.1.12
find-and-replace@0.212.3
fizzy@0.21.0
ide-typescript@0.6.1
intentions@1.1.5
junit-runner@0.0.0
language-batch@0.4.0
language-c@0.58.1
language-clojure@0.22.4
language-coffee-script@0.49.1
language-csharp@0.14.2
language-css@0.42.6
language-gfm@0.90.1
language-git@0.19.1
language-go@0.44.2
language-html@0.47.7
language-hyperlink@0.16.2
language-java@0.27.4
language-javascript@0.127.5
language-json@0.19.1
language-latex@1.1.1
language-less@0.33.0
language-make@0.22.3
language-mustache@0.14.3
language-pegjs@0.5.0
language-php@0.42.0
language-pug@0.0.21
language-ruby@0.71.3
language-sass@0.61.1
language-shellscript@0.25.3
language-sourcepawn@0.7.2
language-sql@0.25.8
language-test@0.0.1
language-todo@0.29.2
language-toml@0.18.1
language-xml@0.35.2
language-yaml@0.31.0
latex@0.47.0
latex-autocomplete@1.0.0
linter@2.2.0
linter-coffeelint@1.3.1
linter-eslint@8.3.2
linter-js-standard@4.0.2
linter-stylelint@4.0.2
linter-ui-default@1.6.10
MagicPython@1.0.12
notifications@0.69.2
pdf-view@0.59.0
script@3.16.0
settings-view@0.251.5
tree-view@0.218.0
```
autocomplete-python, busy-signal, linter, linter-ui-default, MagicPython are disabled.

**Comment by Alhadis** [comment]
When you run `AtomFS.paths` in the dev-console, and expand the entries list... are the path separators uniform across all entries? Or do some still have backslashes as separators? They should all be forwards-facing...

**Comment by 50Wliu** [comment]
Oh hey, look at this.  Want me to file a new issue?  Only happened in Window 1 (which is in dev mode).
```
Uncaught (in promise) TypeError: entity.addEditor is not a function
    at disposables.add.onOpenFile.editor (C:\Users\user\.atom\packages\file-icons\lib\ui.js:39:12)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\user\Documents\GitHub\atom\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\user\Documents\GitHub\atom\node_modules\event-kit\lib\emitter.js:141:28)
    at disposables.add.atom.workspace.observeTextEditors.editor (C:\Users\user\.atom\packages\file-icons\lib\ui.js:66:19)
    at file:///C:/Users/user/Documents/GitHub/atom/out/app/src/workspace.js:621:54
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\user\Documents\GitHub\atom\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\user\Documents\GitHub\atom\node_modules\event-kit\lib\emitter.js:141:28)
    at file:///C:/Users/user/Documents/GitHub/atom/out/app/src/workspace.js:502:22
    at file:///C:/Users/user/Documents/GitHub/atom/out/app/src/workspace.js:502:82
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\user\Documents\GitHub\atom\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\user\Documents\GitHub\atom\node_modules\event-kit\lib\emitter.js:141:28)
    at PaneContainer.didAddPaneItem (C:\Users\user\Documents\GitHub\atom\src\pane-container.js:266:18)
    at Pane.addItem (C:\Users\user\Documents\GitHub\atom\src\pane.js:628:42)
    at Pane.activateItem (C:\Users\user\Documents\GitHub\atom\src\pane.js:570:12)
    at Workspace.<anonymous> (file:///C:/Users/user/Documents/GitHub/atom/out/app/src/workspace.js:1025:12)
    at Generator.next (<anonymous>)
    at step (file:///C:/Users/user/Documents/GitHub/atom/out/app/src/workspace.js:1:12)
```

Have a field day with this.
![image](https://user-images.githubusercontent.com/2766036/30776174-1fc85e4c-a0a2-11e7-9b7e-9d93214e39bc.png)

**Comment by 50Wliu** [comment]
I'm also getting errors from the github package, so maybe it's not just file-icons.

**Comment by Alhadis** [comment]
Are you running a beta version of Atom, or has it been built from master directly?

**Comment by 50Wliu** [comment]
I'm running Atom 1.22.0-dev-f762bf954.  Should have included that, sorry.

**Comment by Alhadis** [comment]
Can you test this in a stable environment, please?

**Comment by 50Wliu** [comment]
Will try to.

**Comment by 50Wliu** [comment]
Ok, as this is happening with literally every new repo I'm cloning, I suspect it may be due to my tree-view Map changes.  I will attempt to report back soon.

**Comment by Alhadis** [comment]
@50Wliu Don't forget to leverage the filesystem API's index (`global.AtomFS.paths`) in case it helps you with debugging. :)

I appreciate the time you're putting towards investigating this.

**Comment by 50Wliu** [comment]
I tried checking out some new repos while on Atom 1.22.0 stable with only file-icons and my syntax theme installed.  While I can't reproduce the incorrect icons right now, I can still confirm that `AtomFS.paths` is reporting a mix of Unix and Windows-style path delimiters.  Directories use Unix-style while Files use Windows-style.

language-csharp is still broken and some entries in the Map map to `undefined`.
![language-csharp-file-icons-grammars](https://user-images.githubusercontent.com/2766036/32634987-a7c5454a-c5ae-11e7-91dd-20720de9b841.png)

**Comment by Alhadis** [comment]
Right, this *should* be solved with the latest release. Could you confirm?

If not the incorrect icons, then certainly the inconsistent path separators. I've [added a speciality class](https://github.com/Alhadis/Atom-FS/blob/0183b79/lib/path-map.js) to help deal with that.

**Comment by 50Wliu** [comment]
> Right, this should be solved with the latest release. Could you confirm?

Whoops, missed this.  I'll get back to you when I have time.

**Comment by 50Wliu** [comment]
![language-csharp-still-broken](https://user-images.githubusercontent.com/2766036/33850104-10b4633e-deb3-11e7-8b79-78a677b5bd02.png)
There is no `language-csharp/grammars` entry in `AtomFS.paths`.

I also see this:
![settings-view-incorrect-spec-icon](https://user-images.githubusercontent.com/2766036/33850127-264ef524-deb3-11e7-8fd1-8ed4cf2a3ce6.png)
The file does exist in `AtomFS.paths` and points to the correct `File`.  Changing languages does nothing.

Atom 1.25.0-dev-3039ac1f4, file-icons@2.1.14.
