### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by Ferux** [file-icons/atom#566]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At C:\Users\Al\.atom\packages\file-icons\lib\consumers\tree-entry.js:52

TypeError: Cannot read property 'destroy' of undefined
    at TreeEntry.destroy (/packages/file-icons/lib/consumers/tree-entry.js:52:17)
    at TreeEntry.disposables.add.source.onDidDestroy (/packages/file-icons/lib/consumers/tree-entry.js:25:56)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:125:28)
    at Directory.module.exports.Directory.destroy (/app.asar/node_modules/tree-view/lib/directory.js:61:27)
    at TreeView.module.exports.TreeView.updateRoots (/app.asar/node_modules/tree-view/lib/tree-view.js:588:24)
    at /app.asar/node_modules/tree-view/lib/tree-view.js:373:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/app.asar/src/project.js:288:29)
    at /app.asar/src/atom-environment.js:1011:40
    at /app.asar/src/application-delegate.js:31:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -7:16.7.0 settings-view:uninstall-packages (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -7:04.1.0 intentions:highlight (input.hidden-input)
     -7:04.0 dash:shortcut (input.hidden-input)
  8x -5:07.9.0 core:backspace (input.hidden-input)
  2x -5:04.3.0 core:confirm (input.hidden-input)
     -4:34.8.0 core:select-all (input.hidden-input)
     -4:33.4.0 core:confirm (input.hidden-input)
 39x -2:48.7.0 core:move-up (input.hidden-input)
 41x -2:45.8.0 core:move-down (input.hidden-input)
     -2:41.5.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.seti-icons.seti-roboto.seti-animate.theme-monokai-slate.theme-seti-ui.seti-theme-steel.seti-compact)
 41x -0:40 core:move-up (input.hidden-input)
     -0:37.9.0 core:move-down (input.hidden-input)
     -0:37.9.0 core:move-up (input.hidden-input)
 37x -0:37.8.0 core:move-down (input.hidden-input)
  6x -0:34.2.0 core:move-up (input.hidden-input)
     -0:24.9.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
busy-signal 1.3.0 
emmet 2.4.3 
file-icons 2.1.1 
go-debug 1.1.0 
go-plus 5.3.4 
go-rename 0.3.0 
go-signature-statusbar 1.2.0 
highlight-line 0.12.0 
highlight-selected 0.12.0 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.1.0 
linter-ui-default 1.2.1 
monokai 0.22.0 
monokai-slate 0.6.0 
platformio-ide-terminal 2.5.0 
Remote-FTP 0.10.7 
seti-ui 1.7.0 
```

**Comment by Alhadis** [comment]
What were you doing right before this happened?

**Comment by TheBrenny** [comment]
Popped this issue after doing the steps in #569 for a second attempt.
