### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getClasses' of undefined

### ISSUE THREAD

**Issue by SukjuneChoi-B2LiNK** [file-icons/atom#567]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getClasses' of undefined

```
At /Users/choisukjune/.atom/packages/file-icons/lib/service/icon-node.js:76

TypeError: Cannot read property 'getClasses' of undefined
    at IconNode.refresh (/packages/file-icons/lib/service/icon-node.js:76:38)
    at IconNode.disposables.add.UI.onMotifChanged._ (/packages/file-icons/lib/service/icon-node.js:27:31)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at UI.emit (/packages/file-icons/lib/ui.js:113:16)
    at UI.emitMotifChanged (/packages/file-icons/lib/ui.js:141:38)
    at UI.checkMotif (/packages/file-icons/lib/ui.js:207:9)
    at Immediate.setImmediate (/packages/file-icons/lib/ui.js:24:29)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -9:34.9.0 core:confirm (input.hidden-input)
     -8:11.7.0 core:paste (input.hidden-input)
     -7:41.6.0 core:confirm (input.hidden-input)
  2x -7:35.5.0 core:backspace (input.hidden-input)
     -7:32.6.0 core:confirm (input.hidden-input)
     -5:53.2.0 core:paste (input.hidden-input)
     -5:50 core:confirm (input.hidden-input)
  4x -4:20.5.0 core:backspace (input.hidden-input)
     -4:18.6.0 core:confirm (input.hidden-input)
  4x -3:55.4.0 core:backspace (input.hidden-input)
     -3:46.3.0 core:confirm (input.hidden-input)
  5x -2:37 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:32.1.0 core:paste (input.hidden-input)
     -2:18 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-nord-atom-ui)
```

### Non-Core Packages

```
file-icons 2.1.1 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.2 
seti-ui-red 0.13.0 
```

**Comment by Alhadis** [comment]
@SukjuneChoi-B2LiNK What were you doing right before this happened? What panels or sidebars were open?

**Comment by Alhadis** [comment]
No response from submitter; closing.

**Comment by krabbypattified** [comment]
Can we reopen this?
I was working on a Django project when I added a `setup.py` file via drag-and-drop.
Then I noticed it wasn't getting an icon, so I went to `file-icons` settings, disabled, and re-enabled it. Then whenever I checked or unchecked the `Coloured` or `Only colour when changed` settings, it gave me this error.

**Comment by Alhadis** [comment]
@krabbypattified Please file a new issue; make sure to include the stack trace, Atom version, OS, and any other pertinent info.

**Comment by krabbypattified** [comment]
Just restarted Atom and that fixed it. Want me to still file a new issue (assuming i can reproduce it)?

**Comment by Alhadis** [comment]
Yes please. =) But do so once it happens.
