### ISSUE TITLE
Cannot read property 'onDidChangeIcon' of undefined (Failed to activate the file-icons package)

### ISSUE THREAD

**Issue by DenisKarakchiev** [file-icons/atom#568]
**Atom Version:** 1.15.0 x64
**System**: Microsoft Windows 10 (10.0.14393 Build 14393)
**Thrown From**: file-icons package, v2.1.1

**Stack-trace**:
```
TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at new IconNode (C:\Users\uoker\.atom\packages\file-icons\lib\service\icon-node.js:30:12)
    at new TreeEntry (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-entry.js:41:19)
    at TreeView.track (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-view.js:82:25)
    at TreeView.rebuild (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-view.js:73:9)
    at TreeView.activate (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-view.js:54:8)
    at TreeView.updateStatus (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\consumer.js:206:9)
    at TreeView.init (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-view.js:30:8)
    at ConsumerManager.init (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\all.js:33:13)
    at Object.activate (C:\Users\uoker\.atom\packages\file-icons\lib\main.js:17:13)
    at Package.module.exports.Package.activateNow (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:218:19)
    at C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:96:15)
    at C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:484:29
    at exit (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:99:16)
    at triggerExitCallback (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by Alhadis** [comment]
Is this a recurring issue, or just a one-off?

**Comment by PhunStyle** [comment]
Same here, but just happens on a new install and on disable/enable. If you enable it and restart atom the icons show up and no warning shows up.

**Failed to activate the file-icons package**
Cannot read property 'onDidChangeIcon' of undefined
```
TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at new IconNode (/home/phun/.atom/packages/file-icons/lib/service/icon-node.js:30:12)
    at new TreeEntry (/home/phun/.atom/packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/home/phun/.atom/packages/file-icons/lib/consumers/tree-view.js:82:25)
    at TreeView.rebuild (/home/phun/.atom/packages/file-icons/lib/consumers/tree-view.js:73:9)
    at TreeView.activate (/home/phun/.atom/packages/file-icons/lib/consumers/tree-view.js:54:8)
    at TreeView.updateStatus (/home/phun/.atom/packages/file-icons/lib/consumers/consumer.js:206:9)
    at TreeView.init (/home/phun/.atom/packages/file-icons/lib/consumers/tree-view.js:30:8)
    at ConsumerManager.init (/home/phun/.atom/packages/file-icons/lib/consumers/all.js:33:13)
    at Object.activate (/home/phun/.atom/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:218:19)
    at /usr/share/atom/resources/app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:96:15)
    at /usr/share/atom/resources/app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:550:34)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by Alhadis** [comment]
This is hopefully temporary. Once the Atom-team merge [`atom/tree-view#1009`](https://github.com/atom/tree-view/pull/1009), post-upgrade/post-install bugs like these will die down.

And even if they don't, they'll be a hell of a lot easier to fix.

In the meantime, there's nothing to worry about unless it's occurring more than once...

**Comment by zauni** [comment]
Unfortunately now it's occurring more than once for me, and also with a slightly different message: `Cannot read property 'path' of undefined`
It doesn't matter if I try to just activate it, or install it, or restarting atom.

Stack Trace:

```
TypeError: Cannot read property 'path' of undefined
    at IconDelegate.deserialise (C:\Users\mzaunseder\.atom\packages\file-icons\lib\service\icon-delegate.js:224:43)
    at new IconDelegate (C:\Users\mzaunseder\.atom\packages\file-icons\lib\service\icon-delegate.js:20:8)
    at IconService.handleResource (C:\Users\mzaunseder\.atom\packages\file-icons\lib\service\icon-service.js:41:16)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at paths.forEach.resource (C:\Users\mzaunseder\.atom\packages\file-icons\node_modules\atom-fs\lib\filesystem.js:150:17)
    at Map.forEach (native)
    at FileSystem.observe (C:\Users\mzaunseder\.atom\packages\file-icons\node_modules\atom-fs\lib\filesystem.js:149:14)
    at IconService.init (C:\Users\mzaunseder\.atom\packages\file-icons\lib\service\icon-service.js:17:15)
    at Object.activate (C:\Users\mzaunseder\.atom\packages\file-icons\lib\main.js:20:15)
    at Package.module.exports.Package.activateNow (C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:218:19)
    at C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:96:15)
    at C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:484:29
    at exit (C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:99:16)
    at triggerExitCallback (C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\mzaunseder\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

file-icons: v2.1.1
Atom: v1.15.0 x64
Windows 10

**Comment by DenisKarakchiev** [comment]
@Alhadis sorry for being late. Yes, it was temporary. But it is appeared several times until i restarted the Atom. Then package successfully installed.

**Comment by sorianog** [comment]
Yep, recurring issue. Just experienced it and got to see this GitHub Issue! 

![file-icons-install-issue](https://cloud.githubusercontent.com/assets/13261711/24427878/1d01494c-13d2-11e7-971f-3113a4064443.png)

**Comment by ChenhuaXu** [comment]
Same here for 2.1.1

**Comment by zauni** [comment]
In my case it's working now, after I installed the latest Win10 Update `KB4015438`. Looks like there were some bugs that even explorer.exe had problems.

**Comment by jonhyleo** [comment]
This is my issue:

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.1


### Stack Trace

Failed to activate the file-icons package

```
At Cannot read property 'onDidChangeIcon' of undefined

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at /packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:82:25)
    at TreeView.rebuild (/packages/file-icons/lib/consumers/tree-view.js:73:9)
    at TreeView.activate (/packages/file-icons/lib/consumers/tree-view.js:54:8)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/consumer.js:206:9)
    at TreeView.init (/packages/file-icons/lib/consumers/tree-view.js:30:8)
    at ConsumerManager.init (/packages/file-icons/lib/consumers/all.js:33:13)
    at Object.activate (/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:48.3.0 core:confirm (input.hidden-input)
     -0:34.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
auto-detect-indentation 1.3.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
busy-signal 1.3.0 
csslint 1.1.5 
emmet 2.4.3 
file-icons 2.1.1 
git-plus 7.3.3 
intentions 1.1.2 
linter 2.1.2 
linter-htmlhint 1.3.2 
linter-jshint 3.0.3 
linter-ui-default 1.2.2 
minimap 4.26.8 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
monokai-seti 0.7.0 
native-ui 0.20.4 
open-recent 5.0.0 
pigments 0.39.1 
seti-ui 1.7.0 
todo-show 1.11.0 
```

**Comment by Commod0re** [comment]
Same issue. Just installed file-icons for the first time. The issue went away (and file icons showed up as expected) after restarting Atom, so maybe that's a good clue?

**Atom**: 1.15.0 x64
**Electron**: 1.4.15
**OS**: "Arch Linux"
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.1


### Stack Trace

Failed to activate the file-icons package

```
At Cannot read property 'onDidChangeIcon' of undefined

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at /packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:82:25)
    at TreeView.rebuild (/packages/file-icons/lib/consumers/tree-view.js:73:9)
    at TreeView.activate (/packages/file-icons/lib/consumers/tree-view.js:54:8)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/consumer.js:206:9)
    at TreeView.init (/packages/file-icons/lib/consumers/tree-view.js:30:8)
    at ConsumerManager.init (/packages/file-icons/lib/consumers/all.js:33:13)
    at Object.activate (/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:218:19)
    at /usr/lib/atom/src/package.js:190:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:96:15)
    at /usr/lib/atom/src/package.js:183:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:542:34)
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:322:11)
    at /usr/lib/atom/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -9:33.7.0 core:confirm (input.hidden-input)
     -8:53 command-palette:toggle (input.hidden-input)
  3x -8:48.5.0 core:backspace (input.hidden-input)
     -8:47.7.0 core:select-all (input.hidden-input)
     -8:38.5.0 editor:consolidate-selections (input.hidden-input)
     -8:38.5.0 core:cancel (input.hidden-input)
  3x -2:38.2.0 core:backspace (input.hidden-input)
     -2:31 core:select-all (input.hidden-input)
     -2:29.5.0 core:confirm (input.hidden-input)
     -2:17.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-live-grammar-reload 0.8.0 
atom-monokai 0.10.7 
file-icons 2.1.1 
graphviz-preview-plus 1.2.1 
language-ansi 1.1.1 
language-apparmor 0.0.0 
language-archlinux 0.9.2 
language-awk 0.1.12 
language-debpkg 0.2.0 
language-dot 1.6.0 
language-ignore 1.5.2 
language-ini 1.17.0 
language-latex 1.0.0 
language-patch 1.2.0 
language-ppd 0.3.1 
language-qml 1.0.0 
language-restructuredtext 1.0.1 
language-roff 1.2.2 
language-svg 0.9.2 
language-syslog-ng 0.0.6 
language-x86-64-assembly 2.2.8 
pigments 0.39.1 
rst-preview-pandoc 0.1.12 
split-diff 1.2.0 
ssh-config 0.10.1 
svg-preview 0.11.0 
```

**Comment by Alhadis** [comment]
Huge apologies for the slow response, sorry. Will cut a patch release shortly: please let me know if this issue persists. Thanks!

**Comment by entr** [comment]
Just happened to me on `v2.1.3` (Atom 1.16.0)

```log
TypeError: Cannot read property 'destroy' of undefined
    at TreeEntry.destroy (/home/zlatev/.atom/packages/file-icons/lib/consumers/tree-entry.js:52:17)
    at TreeEntry.disposables.add.source.onDidDestroy (/home/zlatev/.atom/packages/file-icons/lib/consumers/tree-entry.js:25:56)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:125:28)
    at Directory.module.exports.Directory.destroy (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:61:27)
    at Directory.module.exports.Directory.unwatch (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:221:15)
    at Directory.module.exports.Directory.destroy (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:59:12)
    at Directory.module.exports.Directory.unwatch (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:221:15)
    at Directory.module.exports.Directory.destroy (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:59:12)
    at TreeView.module.exports.TreeView.updateRoots (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:573:24)
    at Object.consumeFileIcons (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:99:14)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:396:71)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:221:16)
    at /usr/share/atom/resources/app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:96:15)
    at /usr/share/atom/resources/app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:550:34)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:352:19
    at /usr/share/atom/resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:173:14)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:353:25)
```
It was working just fine until I disabled it for a bit and enabled it again.

**Comment by Alhadis** [comment]
@entr Did you restart Atom after re-enabling?

Until atom/tree-view#1009 is merged, there's very little I can do to make package disabling bulletproof without restarting.

**Comment by entr** [comment]
@Alhadis that's fine. I didn't realize it's one of those problems. Yes, it's working after a restart. Thanks

**Comment by KSXGitHub** [comment]
I uninstalled 2.1.4, re-installed 2.1.1 and problem gone!

**Comment by Alhadis** [comment]
<img src="https://cloud.githubusercontent.com/assets/2346707/25440228/2142ab5a-2ae2-11e7-9fd0-552c45ff0d15.png" width="596" alt="wat.m{4 * 2}" />

@KSXGitHub u wat m8?

**Comment by KSXGitHub** [comment]
@Alhadis Yeah, I did commented, but when I reactivated it, errors still appear, so I delete my comment

**Comment by Alhadis** [comment]
Can you please file a new issue for this, complete with stack trace? Thanks.

It's clear this is a separate issue.

**Comment by KSXGitHub** [comment]
@Alhadis Maybe it's a separate issue, I wish I could file a new issue with stack trace, but I just re-update to  2.1.4, everything just works, without problems (for no reason).

**Comment by 976500133** [comment]
oh dear , i cannto understand english

**Comment by cliferraren** [comment]
<img width="1310" alt="screen shot 2017-11-21 at 12 25 27 am" src="https://user-images.githubusercontent.com/31750035/33061913-8d10f2c4-ce52-11e7-9a0e-e7e0ea16dcd8.png">

OS: macOS 10.13 High Sierra
Atom Version: 1.22.1

Steps to Reproduce:

1. Installing Package -> file-icons 2.1.14
<img width="761" alt="screen shot 2017-11-21 at 12 32 42 am" src="https://user-images.githubusercontent.com/31750035/33062297-b4ca5f02-ce53-11e7-81e3-38530bbf28f0.png">


Issue: Failed to activate the file-icons package. Cannot read property 'onDidChangeIcon' of undefined

StackTrace:
TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at new IconNode (/Users/rck/.atom/packages/file-icons/lib/service/icon-node.js:30:12)
    at new TreeEntry (/Users/rck/.atom/packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/Users/rck/.atom/packages/file-icons/lib/consumers/tree-view.js:108:25)
    at TreeView.rebuild (/Users/rck/.atom/packages/file-icons/lib/consumers/tree-view.js:98:9)
    at TreeView.activate (/Users/rck/.atom/packages/file-icons/lib/consumers/tree-view.js:71:8)
    at TreeView.updateStatus (/Users/rck/.atom/packages/file-icons/lib/consumers/consumer.js:202:9)
    at TreeView.updateStatus (/Users/rck/.atom/packages/file-icons/lib/consumers/tree-view.js:88:16)
    at TreeView.init (/Users/rck/.atom/packages/file-icons/lib/consumers/tree-view.js:45:8)
    at ConsumerManager.init (/Users/rck/.atom/packages/file-icons/lib/consumers/all.js:32:13)
    at Object.activate (/Users/rck/.atom/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by Alhadis** [comment]
Please restart Atom, then try again. This is a recurring issue that will stop happening with the next Atom release.

**Comment by cliferraren** [comment]
Thanks John for the info.

**Comment by sandakith** [comment]
Thanks for the info. I got the same error and did not encounter it after the restart yet.

**Comment by totovr** [comment]
after restarting Atom the problem continue existing 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.14


### Stack Trace

Failed to activate the file-icons package

```
At Cannot read property 'onDidChangeIcon' of undefined

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at /packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:108:25)
    at TreeView.rebuild (/packages/file-icons/lib/consumers/tree-view.js:98:9)
    at TreeView.activate (/packages/file-icons/lib/consumers/tree-view.js:71:8)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/consumer.js:202:9)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/tree-view.js:88:16)
    at TreeView.init (/packages/file-icons/lib/consumers/tree-view.js:45:8)
    at ConsumerManager.init (/packages/file-icons/lib/consumers/all.js:32:13)
    at Object.activate (/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -0:20 core:confirm (input.hidden-input)
     -0:10.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-material-syntax 1.0.7 
atom-twitter-client 0.4.5 
auto-indent 0.5.0 
comment 0.6.1 
file-icons 2.1.14 
Hydrogen 2.1.0 
markdown-preview-plus 2.4.16 
markdown-writer 2.7.3 
minimap 4.29.7 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
seti-icons 1.5.4 
styri-syntax 0.1.1 
```

**Comment by Alhadis** [comment]
@totovr Did you deactivate and reactivate any of the following packages...?

* `file-icons`
* `tree-view`
* `tabs`
* `fuzzy-finder`
* `find-and-replace`
* `archive-view`

If so, I'm afraid that requires a restart as well. Sorry.

Technically, the issue isn't with installing, but changes in the package's activation status. It'll be fixed in the next release of Atom. 😃

**Comment by totovr** [comment]
Thanks @Alhadis I already did it and now is working! :D

**Comment by mittalyashu** [comment]
I did face the same problem, but it got fixed when I restart the Atom

**Comment by Alhadis** [comment]
This issue is getting an absurd amount of traffic...

![screen shot 2017-12-08 at 3 50 27 pm](https://user-images.githubusercontent.com/2346707/33751534-a23e45b2-dc2f-11e7-914a-24d94c5138b8.png)

@50Wliu Any ETA on Atom v1.23.0? Even a rough estimate?

**Comment by 50Wliu** [comment]
> Any ETA on Atom v1.23.0? Even a rough estimate?

I can't give release dates.  What I can tell you though is that [versions were updated yesterday](https://github.com/atom/atom/commit/b7258bdc8f414b991609f4da731d6a0a9f9e2218), which is a prerequisite to releasing new versions.

**Comment by Alhadis** [comment]
Thank you! That alone makes me feel easier. 😌

**Comment by 50Wliu** [comment]
@Alhadis http://blog.atom.io/2017/12/12/atom-1-23.html
