### ISSUE TITLE
Uncaught TypeError: styleSheet.cssRules[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by Jinnial** [file-icons/atom#572]
[Enter steps to reproduce below:]

1. Open a project folder in atom with html, js, zip, and css files

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Enterprise 2015 LTSB
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.17

### Stack Trace

Uncaught TypeError: styleSheet.cssRules[Symbol.iterator] is not a function

```
At C:\Users\reevesb\.atom\packages\file-icons\lib\ui.js:177

TypeError: styleSheet.cssRules[Symbol.iterator] is not a function
    at UI.getThemeColour (C:\Users\reevesb\.atom\packages\file-icons\lib\ui.js:177:29)
    at UI.checkMotif (C:\Users\reevesb\.atom\packages\file-icons\lib\ui.js:189:23)
    at Immediate.setImmediate (C:\Users\reevesb\.atom\packages\file-icons\lib\ui.js:24:29)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

### Commands

```
  2x -0:02.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoclose-html"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.22 (inactive)
atom-material-ui, v1.3.9 (inactive)
autoclose-html, v0.23.0 (inactive)
browser-refresh, v0.9.0 (inactive)
color-picker, v2.2.5 (inactive)
expose, v0.14.0 (inactive)
file-icons, v2.0.17 (inactive)
HTML-Comment-Color, v0.53.0 (inactive)
html-to-css, v0.2.2 (inactive)
minimap, v4.26.8 (inactive)
print-atom, v0.1.1 (inactive)
project-manager, v3.3.4 (inactive)
script, v3.14.1 (inactive)
template-generator, v0.15.0 (inactive)
tool-bar, v1.1.0 (inactive)
tool-bar-basic, v1.3.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
Why are you using such an old version of Atom?

Upgrade to 1.15 and try again.
