### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by jodarich2** [file-icons/atom#579]
How can I solve the:
TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at new IconNode (C:\Users\uoker\.atom\packages\file-icons\lib\service\icon-node.js:30:12)
    at new TreeEntry (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-entry.js:41:19)
    at TreeView.track (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-view.js:82:25)
    at TreeView.rebuild (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-view.js:73:9)
    at TreeView.activate (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-view.js:54:8)
    at TreeView.updateStatus (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\consumer.js:206:9)
    at TreeView.init (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\tree-view.js:30:8)
    at ConsumerManager.init (C:\Users\uoker\.atom\packages\file-icons\lib\consumers\all.js:33:13)
    at Object.activate (C:\Users\uoker\.atom\packages\file-icons\lib\main.js:17:13)
    at Package.module.exports.Package.activateNow (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:218:19)
    at C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:96:15)
    at C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:484:29
    at exit (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:99:16)
    at triggerExitCallback (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\uoker\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by Alhadis** [comment]
Try restarting Atom.

Let me know if the issue persists.
