### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'D:/...

### ISSUE THREAD

**Issue by eppak** [file-icons/atom#581]
Hello i use this package with Remote-FTP 0.10.7, when i try to browse folder remotely i get this error:

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'D:\MYFOLDER\htdocs\.gitattributes'

```
At fs.js:640

Error: ENOENT: no such file or directory, open 'D:\<<MYFOLDER>>\htdocs\.gitattributes'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at File.loadData (/packages/file-icons/node_modules/atom-fs/lib/file.js:64:10)
    at LinguistStrategy.registerResource (/packages/file-icons/lib/service/strategies/linguist-strategy.js:86:12)
    at LinguistStrategy.check (/packages/file-icons/lib/service/strategy.js:133:9)
    at StrategyManager.query (/packages/file-icons/lib/service/strategy-manager.js:85:32)
    at IconDelegate.getCurrentIcon (/packages/file-icons/lib/service/icon-delegate.js:169:20)
    at IconDelegate.getClasses (/packages/file-icons/lib/service/icon-delegate.js:78:11)
    at IconNode.refresh (/packages/file-icons/lib/service/icon-node.js:76:39)
    at /packages/file-icons/lib/service/icon-node.js:53:8)
    at Function.forElement (/packages/file-icons/lib/service/icon-node.js:177:17)
    at addIconToElement (/packages/file-icons/lib/service/icon-service.js:86:19)
    at FileView.module.exports.FileView.initialize (/packages/Remote-FTP/lib/views/file-view.js:39:29)
    at /packages/Remote-FTP/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/Remote-FTP/lib/views/file-view.js:13:36)
    at /packages/Remote-FTP/lib/views/directory-view.js:138:20
    at Array.forEach (native)
    at DirectoryView.module.exports.DirectoryView.repaint (/packages/Remote-FTP/lib/views/directory-view.js:131:23)
    at /packages/Remote-FTP/lib/views/directory-view.js:58:43
    at /packages/Remote-FTP/node_modules/emissary/lib/emitter.js:155:30
    at Array.forEach (native)
    at Behavior.module.exports.Emitter.emitSlow (/packages/Remote-FTP/node_modules/emissary/lib/emitter.js:154:47)
    at Behavior.module.exports.Emitter.emit (/packages/Remote-FTP/node_modules/emissary/lib/emitter.js:107:30)
    at Behavior.module.exports.Behavior.emit (/packages/Remote-FTP/node_modules/emissary/lib/behavior.js:44:38)
    at Behavior.module.exports.Signal.emitValue (/packages/Remote-FTP/node_modules/emissary/lib/signal.js:82:19)
    at Directory.module.exports.Model.set (/packages/Remote-FTP/node_modules/theorist/lib/model.js:166:21)
    at Directory.set (/packages/Remote-FTP/node_modules/theorist/lib/model.js:57:23)
    at /packages/Remote-FTP/lib/directory.js:140:17
    at /packages/Remote-FTP/lib/client.js:542:57
    at tryApply (/packages/Remote-FTP/lib/connectors/ftp.js:16:14)
    at /packages/Remote-FTP/lib/connectors/ftp.js:165:13
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:451:7)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:46.8.0 intentions:highlight (input.hidden-input)
  2x -0:46.6.0 find-and-replace:select-next (input.hidden-input)
     -0:44.4.0 intentions:highlight (input.hidden-input)
     -0:44.3.0 find-and-replace:show (input.hidden-input)
  7x -0:42.1.0 core:confirm (input.hidden-input)
     -0:38.7.0 editor:consolidate-selections (input.hidden-input)
     -0:38.7.0 core:cancel (input.hidden-input)
     -0:18.3.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
atom-beautify 0.29.17 
atom-typescript 11.0.1 
autoclose-html 0.23.0 
busy-signal 1.3.0 
emmet 2.4.3 
environment 1.3.1 
file-icons 2.1.2 
github-atom-light-syntax 0.3.2 
go-config 1.1.4 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.2 
linter-ui-default 1.2.2 
octocat-syntax 1.3.1 
pumpkin-syntax 0.1.0 
Remote-FTP 0.10.7 
robin-hood-syntax 1.0.0 
terminal-panel 1.14.1 
```

**Comment by Alhadis** [comment]
Crap. Good catch. Glad you picked up on that.

I'll have a look.

**Comment by Alhadis** [comment]
@eppak Are you able to checkout this package's master branch, and tell me if [`67975f0`](https://github.com/file-icons/atom/commit/67975f0089bbdf8e751b796fbe284b768f63c52d) has fixed this?

Open `.atom\dev\packages` in a terminal window, then run:

~~~shell
git clone https://github.com/file-icons/atom.git file-icons
cd file-icons
apm install .
~~~

Quit Atom, then run `atom -d` on the current directory to open Atom in dev-mode. Then try again.

**Comment by eppak** [comment]
Work perfectly, thanks for help!

**Comment by Alhadis** [comment]
Any time!

**Comment by Alhadis** [comment]
I'll cut a patch release in a few days so this will be published. Until then, you can just use the locally-linked version for working around the `.gitattributes` issue. =)
