### ISSUE TITLE
Uncaught Error: Cannot find module '~/AppData\Local\atom\app-1.16.0\resources\app.asar\node_modul...

### ISSUE THREAD

**Issue by reinsle** [file-icons/atom#590]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: GAMER42
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.3

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\reinsle.KE\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tabs\lib\util.js'

```
At module.js:457

Error: Cannot find module 'C:\Users\reinsle.KE\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tabs\lib\util.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Tabs.loadPackageFile (/packages/file-icons/lib/consumers/consumer.js:231:10)
    at Tabs.activate (/packages/file-icons/lib/consumers/tabs.js:50:22)
    at Tabs.updateStatus (/packages/file-icons/lib/consumers/consumer.js:206:9)
    at Immediate.setImmediate (/packages/file-icons/lib/consumers/consumer.js:82:27)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -6:58.3.0 core:select-all (input.hidden-input)
     -6:56.5.0 core:confirm (input.hidden-input)
  2x -6:34.4.0 core:backspace (input.hidden-input)
  2x -6:30.7.0 core:confirm (input.hidden-input)
  5x -5:31.2.0 core:backspace (input.hidden-input)
     -5:30.3.0 core:confirm (input.hidden-input)
  2x -4:26.8.0 core:backspace (input.hidden-input)
     -4:25.9.0 core:confirm (input.hidden-input)
     -2:16.6.0 core:backspace (input.hidden-input)
     -1:57.6.0 application:open-folder (input.hidden-input)
     -1:20.2.0 command-palette:toggle (atom-pane.pane.active)
     -1:16.7.0 core:move-down (input.hidden-input)
     -1:16.4.0 core:confirm (input.hidden-input)
     -1:16.4.0 settings-view:install-packages-and-themes (atom-pane.pane.active)
  2x -1:12.1.0 core:confirm (input.hidden-input)
     -0:17.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-java 1.2.5 
autocomplete-python 1.8.63 
busy 0.7.0 
busy-signal 1.3.0 
file-icons 2.1.3 
git-control 0.9.0 
git-plus 7.6.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
java-classpath-registry 0.4.0 
java-generator 2.2.3 
java-generator-plus 2.6.0 
java-import-wiz 0.5.0 
java-importer 1.4.1 
java-plus 0.1.0 
linter 2.1.4 
linter-javac 1.9.4 
linter-python 3.1.1 
linter-python-pep8 0.2.0 
linter-ui-default 1.2.3 
minimap 4.27.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
open-recent 5.0.0 
project-manager 3.3.4 
project-plus 0.9.0 
python-indent 1.0.2 
python-tools 0.6.9 
todo-show 1.11.0 
```

**Comment by Alhadis** [comment]
> **OS:** GAMER42

What operating system is *that*?

**Comment by Alhadis** [comment]
@reinsle Are any of your core packages disabled? E.g., the `tabs` package?
