### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by wss1942** [file-icons/atom#611]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.7

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeIcon' of undefined

```
At /Users/wangshushuo/.atom/packages/file-icons/lib/service/icon-node.js:30

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at FuzzyFinder.trackEntry (/packages/file-icons/lib/consumers/consumer.js:182:16)
    at timeouts.set.setTimeout (/packages/file-icons/lib/consumers/fuzzy-finder.js:169:10)
```

### Commands

```
     -0:25.5.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:22.7.0 editor:consolidate-selections (input.hidden-input)
     -0:22.7.0 core:cancel (input.hidden-input)
     -0:21.9.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -0:20 editor:consolidate-selections (input.hidden-input)
     -0:20 core:cancel (input.hidden-input)
     -0:19.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
emmet 2.4.3 
file-icons 2.1.7 
git-plus 7.9.3 
minimap 4.28.2 
minimap-git-diff 4.3.1 
react 0.16.2 
svn 0.0.13 
```

**Comment by wss1942** [comment]
I dont know what is happening ,atom alert bugs when use cmd+p to search some file which i want to open.

**Comment by Alhadis** [comment]
@wss1942 Is this the first time you've installed `file-icons`? If so, please restart Atom and try searching again.

**Comment by Alhadis** [comment]
@wss1942 Is this still happening?
