### ISSUE TITLE
Uncaught TypeError: entity.addEditor is not a function

### ISSUE THREAD

**Issue by tonycode** [file-icons/atom#617]
![selection_022](https://user-images.githubusercontent.com/6095724/27316155-7cd8f284-5586-11e7-869e-0f10456ccfe3.png)

A sequence that led to this crash:

1. Create file `Foo.jsx` in `pages` folder
2. Add some file's content
3. Rename this file to `LovManager.jsx`
4. Then drap'n'drop it to folder `another` with came root folder as `pages`. This made in the tree-view panel
5. ! Notice that file's icon have changed to be like a folder
6. Right click on the filename's tab (main panel) and select *Split right*
7. Got that crash, no window split occured...

**Atom**: 1.18.0-beta3 x64
**Electron**: 1.3.15
**OS**: Linux Mint
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.7

### Stack Trace

Uncaught TypeError: entity.addEditor is not a function

```
At /home/tonycode/.atom/packages/file-icons/lib/ui.js:39

TypeError: entity.addEditor is not a function
    at disposables.add.onOpenFile.editor (/packages/file-icons/lib/ui.js:39:12)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.atom.workspace.observeTextEditors.editor (/packages/file-icons/lib/ui.js:66:19)
    at /usr/share/atom-beta/resources/app/src/workspace.js:721:22
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /usr/share/atom-beta/resources/app/src/workspace.js:594:34
    at /usr/share/atom-beta/resources/app/src/workspace.js:595:19
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didAddPaneItem (/usr/share/atom-beta/resources/app/src/pane-container.js:266:24)
    at PaneContainer.didAddPane (/usr/share/atom-beta/resources/app/src/pane-container.js:238:18)
    at Pane.module.exports.Pane.setContainer (/usr/share/atom-beta/resources/app/src/pane.js:149:32)
    at PaneAxis.module.exports.PaneAxis.addChild (/usr/share/atom-beta/resources/app/src/pane-axis.js:154:19)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (/usr/share/atom-beta/resources/app/src/pane-axis.js:225:25)
    at Pane.module.exports.Pane.split (/usr/share/atom-beta/resources/app/src/pane.js:968:29)
    at Pane.module.exports.Pane.splitRight (/usr/share/atom-beta/resources/app/src/pane.js:928:25)
    at TabBarView.module.exports.TabBarView.splitTab (/usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:378:37)
    at Object.TabBarView.addElementCommands.tabs:split-right (/usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:136:32)
    at HTMLUListElement.commandsWithPropagationStopped.(anonymous function) (/usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:82:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom-beta/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom-beta/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/usr/share/atom-beta/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:14.1.0 tabs:close-other-tabs (div.title.icon.icon-file-directory)
  2x -0:11.7.0 tabs:split-right (div.title.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
autoclose-html 0.23.0 
autocomplete 0.47.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.7 
git-log 0.4.1 
git-plus 7.9.3 
hey-pane 1.0.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
js-hyperclick 1.11.0 
jsx-comment 0.2.0 
language-javascript-jsx 0.3.7 
linter-write-good 0.9.0 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
organized 0.6.7 
path-hyperclick 0.3.0 
term 0.2.4 
terminal-fusion 2.4.4 
termination 0.5.1 
```

**Comment by tonycode** [comment]
Actually this is a duplicate of #490, but here we've got crash at `lib/ui.js:39` - maybe there's a need to add some check for undefined

**Comment by Alhadis** [comment]
Hi @tonycode,

I can't reproduce this. Does this still occur after installing Atom v1.18.0? I noticed you're still running a beta version of a now stable release:

> **Atom:** 1.18.0-beta3 x64

**Comment by tonycode** [comment]
Hi, @Alhadis!

You're right, it's gone!

Sorry, I've missed that Atom18 was already released and it's time to drop the beta version (and use git feature from right-pane in main, non-beta package) =)

Issue is no more actual - closing...
