### ISSUE TITLE
Uncaught Error: NOENT on changing git branch

### ISSUE THREAD

**Issue by alflanagan** [file-icons/atom#620]
[Enter steps to reproduce:]

1. Open project folder which is part of a git repo.
2. From command line, check out a different branch of the repo, which is missing a file that is shown in the tree.

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: "Fedora release
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.8

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/aflanagan/Devel/realmatch/api_helper/.gitattributes'

```
At fs.js:558

Error: ENOENT: no such file or directory, open '/home/aflanagan/Devel/realmatch/api_helper/.gitattributes'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at File.loadData (/packages/file-icons/node_modules/atom-fs/lib/file.js:64:10)
    at disposables.add.file.onDidChangeOnDisk._ (/packages/file-icons/lib/service/strategies/linguist-strategy.js:81:37)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at File.emit (/packages/file-icons/node_modules/atom-fs/lib/resource.js:99:17)
    at systemDisposables.events.onDidChange._ (/packages/file-icons/node_modules/atom-fs/lib/file.js:240:33)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at File.module.exports.File.handleNativeChangeEvent (/usr/share/atom-beta/resources/app/node_modules/pathwatcher/lib/file.js:534:37)
    at PathWatcher.<anonymous> (/usr/share/atom-beta/resources/app/node_modules/pathwatcher/lib/file.js:568:54)
    at /usr/share/atom-beta/resources/app/node_modules/pathwatcher/lib/main.js:162:32
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at HandleWatcher.onEvent (/usr/share/atom-beta/resources/app/node_modules/pathwatcher/lib/main.js:81:37)
    at /usr/share/atom-beta/resources/app/node_modules/pathwatcher/lib/main.js:238:51
```

### Commands

```
     -9:47.8.0 core:move-up (input.hidden-input)
     -9:47.1.0 editor:newline (input.hidden-input)
  5x -9:43.5.0 core:backspace (input.hidden-input)
     -9:27.9.0 intentions:highlight (input.hidden-input)
     -9:27.2.0 core:save (input.hidden-input)
     -8:42.3.0 editor:newline (input.hidden-input)
     -8:40.9.0 snippets:next-tab-stop (input.hidden-input)
     -8:40.9.0 snippets:expand (input.hidden-input)
     -8:40.9.0 editor:indent (input.hidden-input)
  4x -8:39.9.0 core:backspace (input.hidden-input)
     -8:38.7.0 snippets:next-tab-stop (input.hidden-input)
     -8:38.7.0 snippets:expand (input.hidden-input)
     -8:38.7.0 editor:indent (input.hidden-input)
     -8:25.7.0 intentions:highlight (input.hidden-input)
     -8:24.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
active-editor-info 0.0.0 
advanced-open-file 0.16.6 
atom-beautify 0.30.3 
atom-keyboard-macros 0.9.2 
atom-live-grammar-reload 0.8.0 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
custom-folds 1.9.4 
disable-keybindings 0.6.0 
django-templates 0.5.0 
editorconfig 2.2.2 
emacs-plus 0.11.1 
export-html 3.1.0 
file-icons 2.1.8 
flex-tool-bar 0.12.0 
git-plus 7.9.3 
go-plus 5.5.5 
goto 1.8.3 
grammar-mode 1.1.0 
Hydrogen 1.18.0 
intentions 1.1.2 
jumpy 3.1.3 
language-babel 2.66.0 
language-forth 0.2.3 
language-javascript-jsx 0.3.7 
language-markdown 0.23.0 
language-mips 0.3.0 
language-powershell 4.0.0 
language-svg 0.9.2 
language-utl 0.1.0 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-coffeescript 1.0.0 
linter-eslint 8.2.1 
linter-gcc 0.7.1 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-phpcs 1.6.7 
linter-pycodestyle 2.0.2 
linter-pydocstyle 0.4.7 
linter-shellcheck 1.4.4 
linter-tidy 2.3.1 
linter-ui-default 1.6.2 
linter-xmllint 1.4.3 
MagicPython 1.0.10 
minimap 4.28.2 
minimap-git-diff 4.3.1 
minimap-linter 2.0.0 
open-html-in-browser 0.1.0 
open-unsupported-files 1.0.20 
php-debug 0.2.4 
project-manager 3.3.5 
python-isort 0.0.7 
python-snippets 1.9.0 
python-tools 0.6.9 
python-yapf 0.14.0 
pythonic-atom 0.2.1 
script 3.15.0 
shell-it 0.2.1 
slickedit-select 1.6.2 
sort-lines 0.14.0 
split-diff 1.4.3 
symbol-quick-pane 0.0.1 
terminal-plus 0.14.5 
tool-bar 1.1.0 
```

**Comment by Alhadis** [comment]
Hey @alflanagan, so sorry I missed this earlier. 👋 

Have you been able to reproduce this problem repeatedly?

**Comment by Alhadis** [comment]
Closing in favour of #620.
