### ISSUE TITLE
Cannot file module './.icondb.js'

### ISSUE THREAD

**Issue by Seamatach** [file-icons/atom#625]
Just installed this package. And am getting this error. My antivirus prompts a warning that it has removed a known virus file from my system when I install this plug in. 

File removed = C:\Users\User\.atom\packages\file-icons\lib\.icondb.js.

Failed to activate the file-icons package
Cannot find module './.icondb.js'
Hide Stack Trace
Error: Cannot find module './.icondb.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\module-cache.js:354:1)
    at Module.require (file:///C:/Users/Matach/AppData/Local/atom/app-1.17.1/resources/app/static/index.js:40:43)
    at require (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\native-compile-cache.js:66:1)
    at new IconTables (C:\Users\Matach\.atom\packages\file-icons\lib\icons\icon-tables.js:18:16)
    at Object.<anonymous> (C:\Users\Matach\.atom\packages\file-icons\lib\icons\icon-tables.js:213:18)
    at Module.get_Module._compile (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///C:/Users/Matach/AppData/Local/atom/app-1.17.1/resources/app/static/index.js:47:45)
    at require (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (C:\Users\Matach\.atom\packages\file-icons\lib\service\icon-delegate.js:7:20)
    at Module.get_Module._compile (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///C:/Users/Matach/AppData/Local/atom/app-1.17.1/resources/app/static/index.js:47:45)
    at require (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (C:\Users\Matach\.atom\packages\file-icons\lib\consumers\tree-entry.js:6:22)
    at Module.get_Module._compile (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///C:/Users/Matach/AppData/Local/atom/app-1.17.1/resources/app/static/index.js:47:45)
    at require (C:\Users\Matach\AppData\Local\atom\app-1.17.1\resources\app\src\native-compile-cache.js:66:1)

The error was thrown from the file-icons package.

Is there anything I can do to make this package work?

**Comment by Alhadis** [comment]
The 'hell kinda antivirus software are you using? It's freaking out over a [plain text file](https://github.com/file-icons/atom/blob/master/lib/icons/.icondb.js), for tchrist's sake. 😕 

Okay, first of all: I'll need you to tell me what antivirus software you have installed, because deleting random JavaScript files really isn't awesome.

Secondly, it'd help if you told me what the program's cited reasons were for deleting that file. Most antivirus programs keep a log or quarantine of the files they remove, along with what triggered the removal.

Obviously, the package isn't going to function without `.icondb.js`... so everything should be fine after the file is restored.

**Comment by Seamatach** [comment]
I am using 360 total security. And its identifying that the file is flagged as the following known malware vulnerability:
virus.js.qexvmc.1070

**Comment by Alhadis** [comment]
Okay, this is pretty bad.
 [Have a read of this](https://isc.sans.edu/forums/diary/Another+Day+Another+Obfuscation+Technique/22354/):

> In this example, we have multiple payloads downloaded with their associated key (no direct PE file), we don't see XOR encryption or Base64 encoding. Nothing suspicious, just plain text!

You may have a comprised package or theme installed. One of which has attempted to download the first segment of a recognised Trojan. Can you give me the list of packages, please?

At this point, I should mention this issue is unrelated to `file-icons`, but there's no way I'm just gonna close this without doing something.

**Comment by Seamatach** [comment]
Themes I just have the core themes. Packages I have the core ones and atom-beautify, color-picker, emmet, file-icons, minimap, and project-manager.

I really haven't done much with packages until just recently as I am starting to use Atom more and more.

**Comment by Alhadis** [comment]
Are you able to reproduce this? Does it happen again when you try reinstalling through the UI?

What happens if you try downloading this [repository's tarball](https://github.com/file-icons/atom/archive/v2.1.8.zip)?
