### ISSUE TITLE
file-icons package cannot read properties of "undefined" and crashes.

### ISSUE THREAD

**Issue by machetazo** [file-icons/atom#628]
[Enter steps to reproduce:]

1. Create New File Under any Directory
2. Expand that folder in tree-view

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeIcon' of undefined

```
At /home/fabian/.atom/packages/file-icons/lib/service/icon-node.js:30

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at /packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:92:25)
    at resource.onDidFindEntries.entries (/packages/file-icons/lib/consumers/tree-view.js:107:64)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TreeEntry.scanEntries (/packages/file-icons/lib/consumers/tree-entry.js:126:18)
    at TreeEntry.disposables.add.source.onDidAddEntries (/packages/file-icons/lib/consumers/tree-entry.js:38:60)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/tree-view/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/tree-view/node_modules/event-kit/lib/emitter.js:125:34)
    at Directory.module.exports.Directory.reload (/usr/share/atom/resources/app/node_modules/tree-view/lib/directory.js:372:35)
    at Directory.module.exports.Directory.expand (/usr/share/atom/resources/app/node_modules/tree-view/lib/directory.js:385:18)
    at DirectoryView.module.exports.DirectoryView.expand (/usr/share/atom/resources/app/node_modules/tree-view/lib/directory-view.js:185:30)
    at DirectoryView.module.exports.DirectoryView.toggleExpansion (/usr/share/atom/resources/app/node_modules/tree-view/lib/directory-view.js:171:27)
    at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:487:30)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:228:32)
```

### Commands

```
     -6:23.4.0 tree-view:remove (li.file.entry.list-item.selected)
     -6:16.5.0 tree-view:add-file (span.name.icon.icon-file-directory)
  2x -6:13.6.0 core:backspace (input.hidden-input)
     -6:10.2.0 core:confirm (input.hidden-input)
     -3:20.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
achievements 0.9.0 
atom-beautify 0.30.4 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
file-icons 2.1.9 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.3 
merge-conflicts 1.4.5 
minimap 4.29.0 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
open-recent 5.0.0 
pane-layout-plus 0.7.3 
pigments 0.39.1 
script 3.15.0 
simple-drag-drop-text 0.3.4 
```

**Comment by Alhadis** [comment]
@machetazo What happened?

**Comment by Alhadis** [comment]
@machetazo Parce, qué pasa? Cual es el chiste? :p

**Comment by machetazo** [comment]
I managed to fix the error by myslef :) thanks!

**Comment by Alhadis** [comment]
Ahuevo! Muy bien!

**Comment by keevinnc92** [comment]
Hola, como solucionaste el error?
gracias!

**Comment by Alhadis** [comment]
Debe reiniciar Atom si reactiva el paquete

Problema temporal.

**Comment by keevinnc92** [comment]
Sí, ya funciona.
muchas gracias por la rapidez.
