### ISSUE TITLE
Cannot find module 'coffee-script' when attempting to compile

### ISSUE THREAD

**Issue by Levertion** [file-icons/atom#636]
```
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.module.exports (C:\Users\Levertion\.atom\packages\file-icons\bin\compile:15:23)
    at process.<anonymous> (C:\Users\Levertion\AppData\Local\atom\app-1.19.0\resources\app\src\task-bootstrap.js:51:41)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This is what seems to be causing #634.
This same module is also referenced in /lib/icons/icon-compiler.js

First noticed on https://github.com/Levertion/atom version whilst adding icons.
Reproduced on fresh install of file-icons package.

Atom: 1.19.0 x64
Windows: 10 home
File icons: 2.1.10

**Comment by Alhadis** [comment]
Let's keep this confined to one issue, please.
