### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/Documents/Projekte/goodgame/CoreJS/nod...

### ISSUE THREAD

**Issue by AndreasPizsa** [file-icons/atom#639]
[Enter steps to reproduce:]

1. ¯\_(ツ)_/¯

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.10

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/apizsa/Documents/Projekte/goodgame/CoreJS/node_modules/tslint/.gitattributes'

```
At fs.js:558

Error: ENOENT: no such file or directory, open '/Users/apizsa/Documents/Projekte/goodgame/CoreJS/node_modules/tslint/.gitattributes'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at File.loadData (/packages/file-icons/node_modules/atom-fs/lib/file.js:64:10)
    at disposables.add.file.onDidChangeOnDisk._ (/packages/file-icons/lib/service/strategies/linguist-strategy.js:81:37)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at File.emit (/packages/file-icons/node_modules/atom-fs/lib/resource.js:99:17)
    at systemDisposables.events.onDidChange._ (/packages/file-icons/node_modules/atom-fs/lib/file.js:240:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at File.module.exports.File.handleNativeChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:534:37)
    at PathWatcher.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:568:54)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:162:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at HandleWatcher.onEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:81:37)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:238:51
```

### Commands

```
     -2:48 snippets:next-tab-stop (input.hidden-input)
     -2:48 snippets:expand (input.hidden-input)
     -2:48 editor:indent (input.hidden-input)
     -2:47.8.0 core:move-up (input.hidden-input)
     -2:47.6.0 docblockr:parse-tab (input.hidden-input)
     -2:47.6.0 snippets:next-tab-stop (input.hidden-input)
     -2:47.6.0 snippets:expand (input.hidden-input)
     -2:47.6.0 editor:indent (input.hidden-input)
     -2:47.4.0 core:move-down (input.hidden-input)
     -2:47.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:46.8.0 core:backspace (input.hidden-input)
     -2:46.6.0 core:save (input.hidden-input)
     -2:46.2.0 core:move-to-bottom (input.hidden-input)
     -2:46 core:save (input.hidden-input)
     -1:31.5.0 core:close (input.hidden-input)
     -0:50.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-coffeescript 1.0.1 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-scss 1.3.1 
atom-auto-prettier 0.1.1 
atom-smart-tabs 0.1.0 
atom-typescript 11.0.6 
autocomplete-js-import 1.4.0 
autocomplete-json 5.5.0 
autocomplete-modules 1.6.10 
blame 0.12.0 
busy-signal 1.4.3 
coffee-refactor 0.7.0 
coffeescript-check 0.2.0 
docblockr 0.11.0 
elastic-tabstops 1.2.0 
file-icons 2.1.10 
git-blame 1.2.1 
hey-pane 1.0.0 
intentions 1.1.5 
javascript-refactor 0.5.7 
js-refactor 0.7.5 
json-colorer 1.0.0 
language-json-comments 0.16.3 
linter 2.2.0 
linter-coffees6 2.0.0 
linter-coffeescript 1.0.0 
linter-eslint 8.2.1 
linter-js-standard 3.9.3 
linter-js-standard-engine 2.1.0 
linter-json-lint 0.1.2 
linter-jsonlint 1.3.0 
linter-tslint 1.7.0 
linter-ui-default 1.6.4 
open-in-browser 0.5.2 
pinned-tabs 1.2.0 
prettier-atom 0.37.0 
refactor 0.11.5 
status-bar-blame 2.0.0 
valign 1.1.3 
```

**Comment by Alhadis** [comment]
Hey mate,

That's a rather unusual error; can you check if there really is a `.gitattributes` file located at the following path? If so, are there any segments in the path which point to symbolically-linked directories?

~~~
~/Documents/Projekte/goodgame/CoreJS/node_modules/tslint/.gitattributes
~~~

It threw when it tried reading from that `.gitattributes` file, because it doesn't expect the fil's contents will be problematic to load...

**Comment by AndreasPizsa** [comment]
Hey @Alhadis,
just checked, this file does indeed exist and all path segments are actual files/directories on my local machine, not symlinks.

🤔

**Comment by AndreasPizsa** [comment]
It just occurred again; I'm running `yarn add <something>` and this happens while yarn is running

**Comment by Alhadis** [comment]
Odd. 😕

Alright, well, the least I can do is silence the error so there's no runtime breakage. For now, you can simply disable this package setting, which should fix the error:

<img src="https://user-images.githubusercontent.com/2346707/29351258-633df0e4-82a5-11e7-91e9-15ff45d07b93.png" width="676" alt="Figure 1" />

**Comment by Alhadis** [comment]
Hey, when I run `yarn add tslint`, I can't see a `.gitattributes` file in `node_modules/tslint`... Did you install it using something else?

**Comment by AndreasPizsa** [comment]
Not that I'm aware of. 🤔

**Comment by Alhadis** [comment]
Yikes. :S That's really strange.

If you installed a list of dependencies using `npm install`, that may explain it.

Either way, please let me know if you encounter this (really weird) issue again, alright? =) Should be fixed by the latest release that I cut earlier today.

**Comment by AndreasPizsa** [comment]
> If you installed a list of dependencies using npm install, that may explain it.

That’s most likely.

Thanks for the fix, @Alhadis ! 👍

**Comment by Alhadis** [comment]
Haha, my pleasure! :D
