### ISSUE TITLE
file-icons package.Uncaught TypeError: Cannot read property 'isDirectory' of undefined

### ISSUE THREAD

**Issue by kobi4ok** [file-icons/atom#643]
[Enter steps to reproduce:]

1. Go to Settings --> Packages;
2. Find "file-icons" package;
3. Move to settings of this packege;
4. Scroll-down and try to mark option "Use custom file-types";

Result: Got error like this:  https://www.screencast.com/t/RYY81s0YX

**Atom**: 1.19.3 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.11

### Stack Trace

Uncaught TypeError: Cannot read property 'isDirectory' of undefined

```
At C:\Users\Vitaliy\.atom\packages\file-icons\lib\service\strategy.js:149

TypeError: Cannot read property 'isDirectory' of undefined
    at UsertypeStrategy.checkAll (/packages/file-icons/lib/service/strategy.js:149:15)
    at UsertypeStrategy.enable (/packages/file-icons/lib/service/strategy.js:80:9)
    at UsertypeStrategy.enable (/packages/file-icons/lib/service/strategies/usertype-strategy.js:44:16)
    at disposables.add.Options.observe.enabled (/packages/file-icons/lib/service/strategy-manager.js:51:24)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at atom.config.observe.value (/packages/file-icons/lib/options.js:132:17)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/config.js:627:22
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.19.3/resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.19.3/resources/app/src/config.js:236:20)
    at SettingsPanel.set (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/settings-view/lib/settings-panel.js:229:27)
    at HTMLInputElement.changeHandler (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/settings-view/lib/settings-panel.js:174:25)
```

### Commands

```
     -4:53 autocomplete-plus:activate (input.hidden-input)
     -4:49.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:48.6.0 intentions:highlight (input.hidden-input)
     -4:48.1.0 core:undo (input.hidden-input)
  3x -4:13.9.0 core:backspace (input.hidden-input)
     -3:56.9.0 autocomplete-plus:cancel (input.hidden-input)
  4x -3:54.7.0 core:backspace (input.hidden-input)
     -3:41.9.0 autocomplete-plus:cancel (input.hidden-input)
     -2:15.7.0 core:backspace (input.hidden-input)
     -2:13.8.0 autocomplete-plus:confirm (input.hidden-input)
     -2:13.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -2:12.3.0 intentions:highlight (input.hidden-input)
     -2:11.8.0 core:undo (input.hidden-input)
     -2:09.5.0 intentions:highlight (input.hidden-input)
     -2:08.9.0 script:run (input.hidden-input)
     -1:49.8.0 pane:split-up-and-copy-active-item (div.line-number.cursor-line)
```

### Non-Core Packages

```
activate-power-mode 2.4.0 
atom-beautify 0.30.5 
atom-clock 0.1.13 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
autocomplete-paths 2.8.1 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.11 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.4.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.7 
minimap 4.29.6 
open-in-browser 0.5.2 
script 3.15.0 
```

**Comment by Alhadis** [comment]
Can't reproduce using those steps. Does this happen after restarting Atom?

**Comment by Alhadis** [comment]
@kobi4ok Can you give us an update? Is this still happening?

**Comment by Alhadis** [comment]
No response from reporter; closing as inconclusive.
