### ISSUE TITLE
Uncaught TypeError: this.childProcess.send is not a function

### ISSUE THREAD

**Issue by DigitalSquid** [file-icons/atom#653]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.12

### Stack Trace

Uncaught TypeError: this.childProcess.send is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/task.js:113

TypeError: this.childProcess.send is not a function
    at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app/src/task.js:113:33)
    at Task.module.exports.Task.start (/Applications/Atom.app/Contents/Resources/app/src/task.js:104:18)
    at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app/src/task.js:23:24)
    at System.sendRequests (/packages/file-icons/node_modules/atom-fs/lib/system.js:88:21)
    at timeoutID._ (/packages/file-icons/node_modules/atom-fs/lib/system.js:51:42)
```

### Commands

```
     -1:26.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
craft-snippets 0.6.3 
craft-twig 0.4.0 
file-icons 2.1.12 
highlight-selected 0.13.1 
jshint 1.8.6 
language-expressionengine-templates 0.1.1 
language-twig 1.6.3 
less-than-slash 0.17.0 
merge-conflicts 1.4.5 
pigments 0.40.2 
project-manager 3.3.5 
```

**Comment by Alhadis** [comment]
I suspect this isn't related to `file-icons`. Going by the stack traces, I'd say Atom's own [`Task.once`](https://github.com/atom/atom/blob/v1.21.0/src/task.coffee#L48) method is to blame for improper cleanup. I suggest [submitting a new issue](https://github.com/atom/atom/issues/new) to the core Atom repository.
