### ISSUE TITLE
Tree View renders blank on project switch with project-manager

### ISSUE THREAD

**Issue by avaly** [file-icons/atom#655]
Using this package together with `project-manager` renders the tree-view blank when switching between projects.

```
Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/usr/share/atom-beta/resources/app/src/item-registry.js:11:21)
    at PaneContainer.didAddPaneItem (/usr/share/atom-beta/resources/app/src/pane-container.js:269:29)
    at PaneContainer.didAddPane (/usr/share/atom-beta/resources/app/src/pane-container.js:242:18)
    at Pane.setContainer (/usr/share/atom-beta/resources/app/src/pane.js:137:23)
    at PaneContainer.setRoot (/usr/share/atom-beta/resources/app/src/pane-container.js:137:21)
    at PaneContainer.deserialize (/usr/share/atom-beta/resources/app/src/pane-container.js:58:16)
    at Dock.deserialize (/usr/share/atom-beta/resources/app/src/dock.js:378:30)
    at Workspace.deserialize (/usr/share/atom-beta/resources/app/src/workspace.js:416:40)
    at /usr/share/atom-beta/resources/app/src/atom-environment.js:1286:35
```

Versions:
`atom`: 1.22.0-beta0
`file-icons`: 2.1.12
`project-manager`: 3.3.5

**Comment by Alhadis** [comment]
👋 Hey @avaly, sorry about the slow response.

I can't seem to reproduce this; are you still experiencing this issue when switching projects?

Could you give me a full list of packages which you have installed, please?

**Comment by avaly** [comment]
For some reason, I can not reproduce this as well today.

However when I saw this 2 days ago, I had disabled all my 3rd party packages and only enabled `project-manager` and `file-icons` packages and saw this error show up. As soon as I disabled the `file-icons` package, the error didn't manifest itself.

Feel free to close for now. I'll open a new ticket if I see this again.

**Comment by Alhadis** [comment]
I *did* notice a discrepancy earlier before while investigating this. Turns out the `tree-view` isn't being patched properly if a user opens a blank window, then adds a folder to their project paths. Still unsure why... likely connected with the architectural changes Atom made when introducing their Docks feature.
