### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by Noobzik** [file-icons/atom#660]
[Enter steps to reproduce:]

1. I've created a new java file
2. Saved it

**Atom**: 1.21.1 ia32
**Electron**: 1.6.15
**OS**: Windows 10 Insider Build 16299.19
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.13

### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At internal/child_process.js:313

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.fork (child_process.js:75:10)
    at new Task (~/AppData/Local/atom/app-1.21.1/resources/app/src/task.js:37:52)
    at Function.module.exports.Task.once (~/AppData/Local/atom/app-1.21.1/resources/app/src/task.js:19:20)
    at System.sendRequests (/packages/file-icons/node_modules/atom-fs/lib/system.js:88:21)
    at timeoutID._ (/packages/file-icons/node_modules/atom-fs/lib/system.js:51:42)
```

### Commands

```
  5x -8:36.3.0 core:backspace (input.hidden-input)
     -8:34.2.0 core:move-up (input.hidden-input)
     -8:34 docblockr:parse-enter (input.hidden-input)
     -8:34 editor:newline (input.hidden-input)
     -8:28.4.0 core:backspace (input.hidden-input)
     -8:25.2.0 core:move-left (input.hidden-input)
     -8:18.4.0 core:backspace (input.hidden-input)
     -8:16.9.0 intentions:highlight (input.hidden-input)
     -8:16.7.0 core:save (input.hidden-input)
     -4:26.2.0 tree-view:add-file (span.name.icon.icon-repo)
  2x -4:17 core:backspace (input.hidden-input)
     -4:14.3.0 core:confirm (input.hidden-input)
     -4:13.2.0 intentions:highlight (input.hidden-input)
     -4:13.1.0 core:paste (input.hidden-input)
     -0:17.7.0 intentions:highlight (input.hidden-input)
     -0:17.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
docblockr 0.11.0 
epitech-norm 0.3.4 
epitech-norm-checker 0.3.1 
fancy-bracket-matcher 2.1.0 
file-icons 2.1.13 
header-42 0.3.3 
intentions 1.1.5 
linter 2.2.0 
linter-gcc 0.7.1 
linter-htmlhint 1.3.4 
linter-javac 1.9.4 
linter-markdown 5.2.0 
linter-ui-default 1.6.10 
markdown-themeable-pdf 1.2.0 
minimap 4.29.7 
monokai 0.24.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
norminette-linter 0.3.1 
pdf-view 0.59.0 
```

**Comment by Alhadis** [comment]
Not related to `file-icons`. Going by the first few lines of that stack trace, I'd say it's something to do with your system or installation:

~~~
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.fork (child_process.js:75:10
~~~
