### ISSUE TITLE
Uncaught TypeError: Cannot read property 'directoryName' of null

### ISSUE THREAD

**Issue by edbrodie** [file-icons/atom#671]
[Enter steps to reproduce:]

1. open/collapse of an empty folder in atom.

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.13

### Stack Trace

Uncaught TypeError: Cannot read property 'directoryName' of null

```
At /Users/edwardbrodie/.atom/packages/file-icons/lib/consumers/tree-entry.js:19

TypeError: Cannot read property 'directoryName' of null
    at /packages/file-icons/lib/consumers/tree-entry.js:19:25)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:108:25)
    at resource.onDidFindEntries.entries (/packages/file-icons/lib/consumers/tree-view.js:123:64)
    at Function.module.exports.Emitter.simpleDispatch (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TreeEntry.scanEntries (/packages/file-icons/lib/consumers/tree-entry.js:133:18)
    at TreeEntry.disposables.add.source.onDidAddEntries (/packages/file-icons/lib/consumers/tree-entry.js:38:60)
    at Function.module.exports.Emitter.simpleDispatch (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/node_modules/event-kit/lib/emitter.js:125:34)
    at Directory.module.exports.Directory.reload (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/directory.js:385:35)
    at Directory.module.exports.Directory.expand (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/directory.js:398:18)
    at DirectoryView.module.exports.DirectoryView.expand (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/directory-view.js:177:30)
    at DirectoryView.module.exports.DirectoryView.toggleExpansion (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/directory-view.js:163:27)
    at TreeView.module.exports.TreeView.entryClicked (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:487:30)
    at HTMLDivElement.<anonymous> (/Users/edwardbrodie/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:228:32)
```

### Commands

```
  4x -7:55.3.0 core:move-right (input.hidden-input)
     -7:54 core:move-down (input.hidden-input)
     -7:53.6.0 autocomplete-plus:confirm (input.hidden-input)
  2x -7:41.4.0 core:backspace (input.hidden-input)
     -7:35.8.0 core:move-right (input.hidden-input)
 15x -7:17.4.0 core:undo (input.hidden-input)
     -5:43.7.0 editor:newline (input.hidden-input)
     -5:43.5.0 core:paste (input.hidden-input)
     -5:32.6.0 core:copy (input.hidden-input)
     -5:31.8.0 core:paste (input.hidden-input)
     -5:31.7.0 editor:newline (input.hidden-input)
     -5:31.5.0 core:paste (input.hidden-input)
     -5:10.1.0 editor:newline (input.hidden-input)
     -4:40.3.0 core:copy (input.hidden-input)
     -4:38.5.0 core:paste (input.hidden-input)
     -4:30.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
auto-indent 0.5.0 
busy-signal 1.4.3 
file-icons 2.1.13 
intentions 1.1.5 
language-babel 2.75.2 
language-ejs 0.4.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-erb 1.1.0 
linter-eslint 8.3.2 
linter-js-yaml 1.2.8 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
open-in-browser 0.5.2 
pigments 0.40.2 
ruby-block 0.3.6 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by Alhadis** [comment]
Unable to reproduce. Did this happen shortly after installing the package? If so, please restart Atom and try again.
