### ISSUE TITLE
failed to activate

### ISSUE THREAD

**Issue by hatchwald** [file-icons/atom#678]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.14

### Stack Trace

Failed to activate the file-icons package

```
At Cannot read property 'onDidChangeIcon' of undefined

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at /packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:108:25)
    at TreeView.rebuild (/packages/file-icons/lib/consumers/tree-view.js:98:9)
    at TreeView.activate (/packages/file-icons/lib/consumers/tree-view.js:71:8)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/consumer.js:202:9)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/tree-view.js:88:16)
    at TreeView.init (/packages/file-icons/lib/consumers/tree-view.js:45:8)
    at ConsumerManager.init (/packages/file-icons/lib/consumers/all.js:32:13)
    at Object.activate (/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:690:42)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.22.1/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.22.1/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -9:00.7.0 core:paste (input.hidden-input)
     -9:00.2.0 core:confirm (input.hidden-input)
     -8:47.9.0 core:move-up (input.hidden-input)
     -8:34.6.0 core:confirm (input.hidden-input)
     -8:25.9.0 core:move-up (input.hidden-input)
 17x -5:39.8.0 core:select-left (input.hidden-input)
     -5:38.7.0 core:move-left (input.hidden-input)
     -5:37.9.0 core:select-all (input.hidden-input)
     -5:37.2.0 core:paste (input.hidden-input)
     -5:36.6.0 core:confirm (input.hidden-input)
     -1:33.3.0 core:select-all (input.hidden-input)
     -1:29.3.0 core:backspace (button.btn.btn-default.selected)
     -1:26.6.0 core:select-all (input.hidden-input)
  4x -1:19.2.0 core:confirm (input.hidden-input)
     -0:42 core:move-down (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:19.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-paths 2.12.1 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.14 
language-blade 0.36.0 
minimap 4.29.7 
platformio-ide-terminal 2.7.0 
```

**Comment by Alhadis** [comment]
Please restart Atom. It's a known issue that's beyond our current ability to fix. See [`#568`](https://github.com/file-icons/atom/issues/568#issuecomment-346527283).

**Comment by hatchwald** [comment]
ew thanks now file icon can work :)

2017-11-29 10:31 GMT+07:00 John Gardner <notifications@github.com>:
