### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by iamxlco** [file-icons/atom#679]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.14

### Stack Trace

Failed to activate the file-icons package

```
At Cannot read property 'onDidChangeIcon' of undefined

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at /packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:108:25)
    at TreeView.rebuild (/packages/file-icons/lib/consumers/tree-view.js:98:9)
    at TreeView.activate (/packages/file-icons/lib/consumers/tree-view.js:71:8)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/consumer.js:202:9)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/tree-view.js:88:16)
    at TreeView.init (/packages/file-icons/lib/consumers/tree-view.js:45:8)
    at ConsumerManager.init (/packages/file-icons/lib/consumers/all.js:32:13)
    at Object.activate (/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:690:42)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.22.1/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.22.1/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
colorpicker 0.3.0 
emmet 2.4.3 
file-icons 2.1.14 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.0 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
```

**Comment by Alhadis** [comment]
Restart Atom.
