### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by NaveenDA** [file-icons/atom#680]
**Atom**: 1.22.1 ia32
**Electron**: 1.6.15
**OS**:  Windows 7 version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.14

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:160

Error: write EPIPE
  at exports._errnoException (util.js:1022:11)
  at ChildProcess.target._send (internal/child_process.js:662:20)
  at ChildProcess.target.send (internal/child_process.js:546:19)
  at Task.module.exports.Task.send (<embedded>:72977:33)
  at Task.module.exports.Task.start (<embedded>:72968:18)
  at Function.module.exports.Task.once (<embedded>:72887:24)
  at System.sendRequests (/packages/file-icons/node_modules/atom-fs/lib/system.js:88:21)
  at timeoutID._ (/packages/file-icons/node_modules/atom-fs/lib/system.js:51:42)

```

### Commands

```
     -0:06.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-bootstrap3 1.2.12 
atom-clock 0.1.15 
atom-fontawesome 0.4.0 
atom-material-syntax-dark 1.0.0 
atom-monokai 0.10.9 
atom-monokai-php 1.0.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.14 
hyperclick 0.1.5 
ide-php 0.7.3 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-apache 1.8.0 
language-blade 0.37.0 
language-dotenv 1.1.1 
laravel 0.7.1 
laravel-helper 0.2.2 
linter 2.2.0 
linter-php 1.5.1 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
monokai 0.24.0 
php-cs-fixer 4.1.1 
php-fmt 0.1.2 
php-integrator-navigation 1.2.1 
platformio-ide-terminal 2.7.0 
selection-highlight 0.1.6 
```

**Comment by Alhadis** [comment]
@NaveenDA Is your `file-icons` package very recently installed? If so, try restarting Atom. :) 

Please let me know too if this exception is thrown more than once and from within different sessions/editor windows.

**Comment by NaveenDA** [comment]
I am install this 2 days before

**Comment by Alhadis** [comment]
Is this the first time this has happened?

**Comment by NaveenDA** [comment]
Yes this happened at only one time

**Comment by Alhadis** [comment]
Alright, now that I've sat down and taken a proper look at the stack trace you've posted, I'd say this is an internal error. That is, something not related to this package:

~~~
Error: write EPIPE
	at exports._errnoException (util.js:1022:11)
	at ChildProcess.target._send (internal/child_process.js:662:20)
	at ChildProcess.target.send (internal/child_process.js:546:19)
…
	at System.sendRequests (/packages/file-icons/node_modules/atom-fs/lib/system.js:88:21)
	at timeoutID._ (/packages/file-icons/node_modules/atom-fs/lib/system.js:51:42)
~~~

Everything except the last two lines points to either Atom or Electron-specific code. So either it's a bug with their codebase, or (much more likely), some memory-related or Windows-specific error.

If you're repeatedly experiencing this problem, you should [file an issue](https://github.com/atom/atom/issues) to the Atom team. Be sure to include as much information as possible.
