### ISSUE TITLE
Failed to activate the file-icons package

### ISSUE THREAD

**Issue by mukkamal** [file-icons/atom#681]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.14

### Stack Trace

Failed to activate the file-icons package

```
At Cannot read property 'onDidChangeIcon' of undefined

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at /packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:108:25)
    at TreeView.rebuild (/packages/file-icons/lib/consumers/tree-view.js:98:9)
    at TreeView.activate (/packages/file-icons/lib/consumers/tree-view.js:71:8)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/consumer.js:202:9)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/tree-view.js:88:16)
    at TreeView.init (/packages/file-icons/lib/consumers/tree-view.js:45:8)
    at ConsumerManager.init (/packages/file-icons/lib/consumers/all.js:32:13)
    at Object.activate (/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (/private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/private/var/folders/fm/vp0xpstn5dj49vnxvq4ztb280000gn/T/AppTranslocation/226147A6-3AF5-4A4D-9988-5CCB9670596B/d/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -0:32.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-predawn-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
busy-signal 1.4.3 
file-icons 2.1.14 
intentions 1.1.5 
linter 2.2.0 
linter-rubocop 2.2.0 
linter-ui-default 1.6.10 
predawn-syntax 1.0.4 
script 3.17.3 
```

**Comment by Alhadis** [comment]
Please restart Atom, and the problem will fix itself. See https://github.com/file-icons/atom/issues/678#issuecomment-347742330.

**Comment by jt3k** [comment]
after restart  the problem not fixed

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.14


### Stack Trace

Failed to activate the file-icons package

```
At Error parsing /Users/a.gurtovoy/.atom/packages/file-icons/node_modules/unset-value/node_modules/has-value/package.json: Unexpected end of JSON input

SyntaxError: Error parsing /Users/a.gurtovoy/.atom/packages/file-icons/node_modules/unset-value/node_modules/has-value/package.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:183:20)
    at Module._resolveFilename (module.js:468:25)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/node_modules/unset-value/index.js:11:11)
    at /packages/file-icons/node_modules/unset-value/index.js:34:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/node_modules/cache-base/index.js:8:11)
    at /packages/file-icons/node_modules/cache-base/index.js:263:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/node_modules/base/index.js:5:17)
    at /packages/file-icons/node_modules/base/index.js:437:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
aesthetic-ui 4.0.0 
atom-ide-ui 0.6.0 
atom-like-brackets-editor 1.2.0 
atom-material-ui 2.0.6 
atom-monokai 0.10.9 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
blame 1.0.1 
busy-signal 1.4.3 
color-tabs 0.1.8 
colorful-json 1.1.0 
comment 0.6.1 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.14 
filecolor 0.4.0 
fold-functions 0.5.0 
fold-lines 0.2.2 
git-blame 1.3.1 
git-control 0.9.0 
git-plus undefined 
git-status 0.3.4 
git-time-machine 1.5.9 
guess-indent 0.1.0 
highlight-bad-chars 1.0.7 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-typescript 0.6.1 
indent-detective 0.1.1 
indent-guide-improved 1.4.13 
indent-toggle-on-paste 0.1.3 
indent-tooltip 0.3.1 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-dot-template 0.2.0 
language-javascript-jsx 0.3.7 
language-mjml 1.10.0 
language-plantuml 0.2.0 
language-postcss 1.3.1 
language-pug 0.0.21 
language-twig 1.6.3 
language-volt 0.2.2 
lines 0.13.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
linter-xo 0.23.1 
markdown-folder 0.5.0 
markdown-scroll-sync 2.1.2 
monokai 0.24.0 
monokai-seti 0.9.0 
motepair 0.24.0 
npm-install 4.0.4 
npm-plus 0.4.0 
pigments 0.40.2 
plantuml-viewer 0.7.2 
platformio-ide-terminal 2.7.0 
prettier-atom 0.43.0 
project-manager 3.3.5 
prompt-big-file 0.4.0 
react 0.17.0 
react-snippets 1.0.1 
remember-folds 0.3.0 
semanticolor 3.5.5 
set-syntax 0.4.0 
seti-ui 1.9.0 
simple-drag-drop-text 0.3.6 
styles-highlighter 2.4.0 
Stylus 3.1.1 
stylus-autocompile 0.6.1 
sublime-block-comment 0.5.1 
svg-preview 0.12.1 
sync-settings 0.8.3 
tool-bar-markdown-writer 0.3.0 
trailing-spaces 0.4.0 
turbo-javascript 1.4.0 
umd-snippets 0.1.1 
```

**Comment by Alhadis** [comment]
Okay, that's actually a very different issue, but still an unrelated one. It sounds like something didn't download correctly, and you were installing from command-line:

At Error parsing /Users/a.gurtovoy/.atom/packages/file-icons/node_modules/unset-value/node_modules/has-value/package.json: Unexpected end of JSON input

~~~
SyntaxError: Error parsing /Users/a.gurtovoy/.atom/packages/file-icons/node_modules/unset-value/node_modules/has-value/package.json: Unexpected end of JSON input
~~~

You should be able to fix this by clearing your local cache and trying again. Just follow [these steps](https://github.com/file-icons/atom/blob/master/README.md#installation-halts-with-an-npm-error). Let me know if you're still having troubles.=)

**Comment by jt3k** [comment]
solved. thanx
