### ISSUE TITLE
Failed to activate the file-icons package

### ISSUE THREAD

**Issue by jerrycavill** [file-icons/atom#694]
`

1. While working a project. I tried to install package

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.15

### Stack Trace

Failed to activate the file-icons package

```
At Cannot read property 'onDidChangeIcon' of undefined

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at /packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:108:25)
    at TreeView.rebuild (/packages/file-icons/lib/consumers/tree-view.js:98:9)
    at TreeView.activate (/packages/file-icons/lib/consumers/tree-view.js:71:8)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/consumer.js:202:9)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/tree-view.js:88:16)
    at TreeView.init (/packages/file-icons/lib/consumers/tree-view.js:45:8)
    at ConsumerManager.init (/packages/file-icons/lib/consumers/all.js:32:13)
    at Object.activate (/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -9:57.3.0 autoclose-html:close-and-complete (input.hidden-input)
  2x -9:54.8.0 core:backspace (input.hidden-input)
     -9:53.2.0 core:undo (input.hidden-input)
  2x -9:50.8.0 core:backspace (input.hidden-input)
     -9:47.8.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -9:47.8.0 snippets:next-tab-stop (input.hidden-input)
     -9:47.8.0 snippets:expand (input.hidden-input)
     -9:47.8.0 editor:indent (input.hidden-input)
     -9:46 emmet:insert-formatted-line-break-only (input.hidden-input)
     -9:46 editor:newline (input.hidden-input)
     -9:44.3.0 core:backspace (input.hidden-input)
     -9:42.9.0 autoclose-html:close-and-complete (input.hidden-input)
  2x -9:42 core:save (input.hidden-input)
     -0:45.3.0 core:confirm (input.hidden-input)
     -0:28 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
compass 0.9.1 
emmet 2.4.3 
file-icons 2.1.15 
merge-conflicts 1.4.5 
php-twig 4.0.0 
platformio-ide-terminal 2.7.0 
sass-autocompile 0.13.3 
tabs-to-spaces 1.0.3 
```

`

**Comment by Alhadis** [comment]
Update your version of Atom.  It's too old.

**Comment by jerrycavill** [comment]
Thank you for the quick response. My version says it's up to date. The install did work after I closed my project and tried again.
