### ISSUE TITLE
Failed to activate the file-icons package

### ISSUE THREAD

**Issue by LeFlow** [file-icons/atom#695]
1. I can't unfortunately install "file-icons" package
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.1.7

### Stack Trace

Failed to activate the file-icons package

```
At Cannot read property 'onDidChangeIcon' of undefined

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at new IconNode (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\service\icon-node.js:30:12)
    at new TreeEntry (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\consumers\tree-entry.js:41:19)
    at TreeView.track (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\consumers\tree-view.js:108:25)
    at TreeView.rebuild (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\consumers\tree-view.js:98:9)
    at TreeView.activate (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\consumers\tree-view.js:71:8)
    at TreeView.updateStatus (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\consumers\consumer.js:202:9)
    at TreeView.updateStatus (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\consumers\tree-view.js:88:16)
    at TreeView.init (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\consumers\tree-view.js:45:8)
    at ConsumerManager.init (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\consumers\all.js:32:13)
    at Object.activate (C:\Users\Florent PRIEUR\.atom\packages\file-icons\lib\main.js:17:13)
    at Package.module.exports.Package.activateNow (C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:183:20)
    at C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:460:29
    at exit (C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Florent PRIEUR\AppData\Local\atom\app-1.11.2\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

### Commands

```
     -9:28.7.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -2:22.3.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -2:17.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:57.7.0 tree-view:move (span.name.icon.icon-file-text)
  4x -1:55.7.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -1:53.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:46.9.0 tree-view:move (span.name.icon.icon-file-text)
 12x -1:45.3.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  3x -1:43.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:41.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:36 tree-view:move (span.name.icon.icon-file-text)
 11x -1:34.5.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  4x -1:32.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:30 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.file-colors)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-less, v0.1.10 (active)
autoprefixer, v3.6.0 (inactive)
emmet, v2.4.3 (active)
file-icons, v2.1.7 (inactive)
logo-file-icons, v1.12.0 (active)
platformio-ide-terminal, v2.4.0 (active)
sass-autocompile, v0.13.3 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

Thank you for you precious help

**Comment by Alhadis** [comment]
Yikes. You're running a really old version of Atom, and you need to install the newer version of the editor manually, I'd say. Normally Atom will auto-update itself for you, but I don't think that feature's working too well for your installation... 😉

**Comment by LeFlow** [comment]
Oh yes, actually, I thought I was up to date.
Sorry.
Everything is OK.
Thank you very much for your help.

**Comment by sniperTon** [comment]
TypeError: Cannot redefine property: _FileIcons
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/Users/wd/.atom/packages/atom/lib/debug.js:64:8)
    at Object.<anonymous> (/Users/wd/.atom/packages/atom/lib/debug.js:71:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/wd/.atom/packages/atom/lib/icons/auto-compiler.js:9:22)
    at Object.<anonymous> (/Users/wd/.atom/packages/atom/lib/icons/auto-compiler.js:181:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/wd/.atom/packages/atom/lib/main.js:6:24)
    at Object.<anonymous> (/Users/wd/.atom/packages/atom/lib/main.js:37:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)

**Comment by Alhadis** [comment]
The answer's in the first few lines:

> **TypeError: Cannot redefine property:** `_FileIcons`

You appear to be instrumenting code or doing something that's monkey-patching packages or globals in your setup... Was were the latest packages you installed for Atom?

The reason this was breaking is because the `_FileIcons` global is frozen after it finishes setting up.

~~~
TypeError: Cannot redefine property: _FileIcons
	at Function.defineProperty ()
	at Object. (/Users/wd/.atom/packages/atom/lib/debug.js:64:8)
	at Object. (/Users/wd/.atom/packages/atom/lib/debug.js:71:3)
~~~

**Comment by king-Senior** [comment]
Failed to activate the file-icons package
Cannot find module 'alhadis.utils'
Show Stack Trace
I hope I can get help

I installed the latest version
thanks！

**Comment by Alhadis** [comment]
@king-Senior How did you install this package? The dependencies should have been automatically installed for you.

You can fix this by `cd`ing to the package's directory and running `apm install`. If that command fails, run `npm install` instead.

**Comment by king-Senior** [comment]
@Alhadis 
npm install  hint found 0 vulnerabilities
apm install hint  Installing modules done
just  Cannot find module 'alhadis.utils'

**Comment by Alhadis** [comment]
Wipe out the contents of your `~/ atom/.apm` folder then try installing again using `apm install file-icons`.

**Comment by king-Senior** [comment]
@Alhadis  
The file-icons have been downloaded
Cannot find module 'alhadis.utils'
