### ISSUE TITLE
Uncaught Error: spawn EPERM

### ISSUE THREAD

**Issue by nofuck** [file-icons/atom#715]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.17

### Stack Trace

Uncaught Error: spawn EPERM

```
At internal/child_process.js:313

Error: spawn EPERM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.fork (child_process.js:75:10)
    at new Task (~/AppData/Local/atom/app-1.24.0/resources/app/src/task.js:37:52)
    at Function.module.exports.Task.once (~/AppData/Local/atom/app-1.24.0/resources/app/src/task.js:19:20)
    at System.sendRequests (/packages/file-icons/node_modules/atom-fs/lib/system.js:88:21)
    at timeoutID._ (/packages/file-icons/node_modules/atom-fs/lib/system.js:51:42)
```

### Commands

```
  3x -8:30.3.0 core:confirm (input.hidden-input)
     -6:25.1.0 command-palette:toggle (div.package-detail.panels-item)
  2x -6:20.3.0 core:move-down (input.hidden-input)
     -6:19.8.0 core:move-up (input.hidden-input)
     -6:18.2.0 core:confirm (input.hidden-input)
     -6:18.2.0 sync-settings:backup (div.package-detail.panels-item)
     -3:48.3.0 core:close (div.package-detail.panels-item)
     -0:32.7.0 intentions:highlight (input.hidden-input)
     -0:32.6.0 core:select-all (input.hidden-input)
     -0:31.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.0 
atom-ide-ui 0.9.3 
autocomplete-modules 1.12.0 
build-dockerfile 1.0.1 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.13.7 
docker 0.8.0 
dockerletion 0.2.0 
file-icons 2.1.17 
git-plus 7.10.0 
go-debug 1.6.0 
go-plus 5.8.2 
go-signature-statusbar 1.2.3 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-go 0.7.0 
ide-php 0.7.9 
insert-timestamp 0.2.4 
intentions 1.1.5 
jsonlint 1.1.4 
language-docker 1.1.8 
language-mongodb 0.3.1 
language-protobuf 0.7.1 
language-swoole 0.3.1 
linter 2.2.0 
linter-jsonlint 1.3.0 
linter-protocol-buffer 0.2.0 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
markdown-pdf 2.1.0 
markdown-preview-enhanced 0.15.2 
minimap 4.29.8 
platformio-ide-terminal 2.8.0 
project-manager 3.3.5 
qolor 0.4.2 
sync-settings 0.8.5 
tablr 1.8.3 
```

**Comment by Alhadis** [comment]
Not related to this package. It has something to do with your system or Atom installation.

~~~
At internal/child_process.js:313

Error: spawn EPERM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.fork (child_process.js:75:10)
    at new Task (~/AppData/Local/atom/app-1.24.0/resources/app/src/task.js:37:52)
~~~

You should report this to the [Atom team](https://github.com/atom/atom/issues/new).
