### ISSUE TITLE
BUG：ui.js entity.addEditor is not a function

### ISSUE THREAD

**Issue by youngjuning** [file-icons/atom#716]
Uncaught (in promise) TypeError: entity.addEditor is not a function
    at disposables.add.onOpenFile.editor

**Comment by ericcornelissen** [comment]
I'm having the same issue, here is how you may be able to reproduce it (I'm on Windows 10):

1. Clone [this](https://git.fsfe.org/pmpc/website) repository
2. Open the repository in Atom
3. Open the file `site/build/build.sh`

**Comment by Alhadis** [comment]
Guys, when you see errors like this, please include the stack-trace. That's the single most important part of a bug report, because it pinpoints where things are going wrong and how they can be fixed.

I'm away-from-Atom at the moment, but I'll try looking into this soon.

Please also tell me what version of Atom you're running.

**Comment by ericcornelissen** [comment]
I'm running Atom 1.24.1 and here is my stacktrace:
```
Uncaught (in promise) TypeError: entity.addEditor is not a function
    at disposables.add.onOpenFile.editor (C:\Users\erico\.atom\packages\file-icons\lib\ui.js:40:12)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at disposables.add.atom.workspace.observeTextEditors.editor (C:\Users\erico\.atom\packages\file-icons\lib\ui.js:68:19)
    at C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\src\workspace.js:732:22
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\src\workspace.js:586:34
    at C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\src\workspace.js:587:19
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at PaneContainer.didAddPaneItem (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\src\pane-container.js:270:24)
    at Pane.addItem (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\src\pane.js:632:48)
    at Pane.activateItem (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\src\pane.js:574:18)
    at Workspace.<anonymous> (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\src\workspace.js:1178:20)
    at Generator.next (<anonymous>)
    at step (C:\Users\erico\AppData\Local\atom\app-1.24.1\resources\app\src\workspace.js:11:279)
```

**Comment by youngjuning** [comment]
My Atom version is 1.25.0 beta3

**Comment by DmitryKozyrenko** [comment]
Same problem. Atom v1.25.1. But on my laptop with the same OS (Windows 10) and the same Atom version and packages I havn't this problem, and this was strange.

`Uncaught (in promise) TypeError: entity.addEditor is not a function
    at disposables.add.onOpenFile.editor (C:\Users\Dmitry\.atom\packages\file-icons\lib\ui.js:40:22)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at disposables.add.atom.workspace.observeTextEditors.editor (C:\Users\Dmitry\.atom\packages\file-icons\lib\ui.js:68:19)
    at onDidAddTextEditor (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\src\workspace.js:638:60)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at onDidAddPaneItem (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\src\workspace.js:519:28)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at PaneContainer.didAddPaneItem (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\src\pane-container.js:271:24)
    at Pane.addItem (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\src\pane.js:632:48)
    at Pane.activateItem (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\src\pane.js:574:18)
    at Workspace.open (C:\Users\Dmitry\AppData\Local\atom\app-1.25.1\resources\app\src\workspace.js:1042:18)
    at <anonymous>`

**Comment by Alhadis** [comment]
Can you reproduce this error consistently, or is just a one-off occurrence?

**Comment by DmitryKozyrenko** [comment]
Yes, same situation happened on my laptop, same packages and Atom version.

> how many tabs you had open

~5-10, but this was occurs if open tabs one by one too, i mean opening one tab then close and opening another one.

> and what editor commands you're running to invoke the error?

Simple file opening. I want to note that file not opening after first double-click, only after second one, but I think it happens because error in console. For better understanding added screenshot.

![atom](https://user-images.githubusercontent.com/29832979/38458205-4add4074-3aa4-11e8-8857-5aa9e2c43911.jpg)

P.S. Sry for bad English.
