### ISSUE TITLE
Uncaught Error: ENXIO: no such device or address, uv_cwd

### ISSUE THREAD

**Issue by codyghind** [file-icons/atom#725]
Steps to reproduce:

1. Open new Project folder containing incompatible file

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.19

### Stack Trace

Uncaught Error: ENXIO: no such device or address, uv_cwd

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:11

Error: ENXIO: no such device or address, uv_cwd
    at process.cwd (/app.asar/node_modules/graceful-fs/polyfills.js:11:19)
    at process.cwd (/app.asar/node_modules/graceful-fs/polyfills.js:11:19)
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:391:17)
    at Module._resolveFilename (module.js:461:31)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Function.resolve (internal/module.js:27:19)
    at Function.customRequire.resolve (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:337606:20)
    at new Task (/Applications/Atom.app/Contents/Resources/app/src/task.js:37:65)
    at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app/src/task.js:19:20)
    at System.sendRequests (/packages/file-icons/node_modules/atom-fs/lib/system.js:88:21)
    at timeoutID._ (/packages/file-icons/node_modules/atom-fs/lib/system.js:51:42)
```

### Commands

```
     -6:46.5.0 core:paste (input.hidden-input)
     -6:43.8.0 core:save (input.hidden-input)
     -6:42.1.0 core:undo (input.hidden-input)
     -6:35.5.0 markdown-writer:insert-new-line (input.hidden-input)
     -6:35.4.0 editor:newline (input.hidden-input)
  3x -6:33.6.0 core:move-down (input.hidden-input)
     -6:32.2.0 core:backspace (input.hidden-input)
     -6:27.1.0 core:select-all (input.hidden-input)
  2x -6:23.6.0 core:copy (input.hidden-input)
     -6:14.2.0 core:save (input.hidden-input)
     -3:33.6.0 markdown-writer:insert-new-line (input.hidden-input)
     -3:33.5.0 editor:newline (input.hidden-input)
     -3:29.2.0 core:save (input.hidden-input)
     -0:35.8.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -0:27.4.0 application:add-project-folder (atom-pane.pane)
  6x -0:02.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-ide-ui 0.11.1 
atom-jinja2 0.6.0 
atom-python-run 0.9.6 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-clang 0.11.4 
autocomplete-java 1.2.7 
autocomplete-json 5.5.2 
autocomplete-modules 2.0.0 
autocomplete-python 1.10.5 
autocomplete-xml 0.9.4 
busy-signal 1.4.3 
copy-filename 1.1.0 
copy-path 0.5.1 
coverage 0.6.1 
file-icons 2.1.19 
git-blame 1.6.0 
git-commit 1.5.3 
git-control 0.9.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 7.10.2 
git-projects 1.17.0 
git-status 0.3.4 
git-time-machine 1.5.9 
gitlab 0.1.3-7 
gitlab-integration 0.4.7 
highlight-selected 0.13.1 
Hydrogen 2.4.1 
ide-bash 1.0.11 
ide-clangd 0.3.0 
ide-cpp 0.0.3 
ide-go 0.7.0 
ide-html 0.4.2 
ide-java 0.8.3 
ide-json 0.2.1 
ide-python 0.9.2 
ide-yaml 0.4.3 
intentions 1.1.5 
language-ansible 0.2.2 
language-docker 1.1.8 
language-markdown 0.25.1 
linter 2.2.0 
linter-ansible-linting 1.3.2 
linter-ansible-syntax 1.2.0 
linter-clang 4.1.2 
linter-csslint 2.0.1 
linter-docker 0.3.2 
linter-flake8 2.3.0 
linter-flint 1.0.1 
linter-gcc 0.7.1 
linter-golinter 1.2.2 
linter-javac 1.9.4 
linter-js-yaml 1.3.0 
linter-jsonlint 1.3.0 
linter-markdown 5.2.1 
linter-ruby 1.2.6 
linter-shellcheck 1.4.7 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
linter-xmllint 1.4.3 
markdown-writer 2.7.3 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
python-indent 1.1.5 
python-tools 0.6.9 
remote-sync 4.1.8 
sync-settings 0.8.6 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.5.0 
```

**Comment by Alhadis** [comment]
These issues are always bizarre. This part seems to suggest the `CWD` wasn't even *available*:
~~~
Error: ENXIO: no such device or address, uv_cwd
    at process.cwd (/app.asar/node_modules/graceful-fs/polyfills.js:11:19)
~~~
... which seems impossible for any running process. :S

@codyghind How many files did you have open when this occurred? Was there a lot of system reads and writes happening in the workspace at the time? And has this happened more than once?

**Comment by Alhadis** [comment]
Closing this because it isn't technically related to this package (as indicated by the call sites listed in the stack trace).

Please open a new issue if this happens again. Make sure to include answers to the same questions I asked earlier.
