### ISSUE TITLE
Cannot Find module 'pseudomap', this error dont let me use file-icons

### ISSUE THREAD

**Issue by Rusbelllozano** [file-icons/atom#764]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.25

### Stack Trace

Failed to activate the file-icons package

```
At Cannot find module 'pseudomap'

Error: Cannot find module 'pseudomap'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.31.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.31.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/node_modules/lru-cache/index.js:7:11)
    at /packages/file-icons/node_modules/lru-cache/index.js:469:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/lib/storage.js:5:18)
    at /packages/file-icons/lib/storage.js:347:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/lib/main.js:4:25)
    at Object.activate (/packages/file-icons/lib/main.js:11:8)
    at Package.activateNow (~/AppData/Local/atom/app-1.31.2/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.31.2/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.31.2/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.31.2/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.31.2/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.31.2/resources/app/src/package-manager.js:696:42)
    at ~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.31.2/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (~/AppData/Local/atom/app-1.31.2/resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
 31x -6:00.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.25 
language-vue 0.23.1 
pigments 0.40.2 
```

**Comment by Alhadis** [comment]
Hi @Rusbelllozano,

It sounds like you haven't installed the package dependencies yet. They should normally be installed automatically when you install `file-icons` through Atom's interface...

How did you install this package? Did you use the **Settings** panel, or install using `apm install file-icons`?
