### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by chebahmed** [file-icons/atom#768]
[Enter steps to reproduce:]

1. ...(see commands below)

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.26

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:323

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:514:9)
    at Object.exports.fork (child_process.js:115:10)
    at /app.asar/src/task.js:35:40)
    at Function.module.exports.Task.once (/app.asar/src/task.js:17:14)
    at System.sendRequests (/packages/file-icons/node_modules/atom-fs/lib/system.js:86:21)
    at timeoutID.setTimeout (/packages/file-icons/node_modules/atom-fs/lib/system.js:50:44)
```

### Commands

```
alias Atom='"/cygdrive/c/Profiles/user/AppData/Local/atom/app-1.32.0/atom.exe" '
Atom file.sh
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-jinja2 0.6.0 
atom-salt 2.0.0 
auto-save-on-idle 1.2.1 
file-icons 2.1.26 
highlight-selected 0.14.0 
markdown-preview-enhanced 0.15.7 
minimap 4.29.9 
```

**Comment by Alhadis** [comment]
This isn't caused by the `file-icons` package, but by something in Atom's core.

If this still happens, I recommend filling an issue upstream.
