### ISSUE TITLE
Error:  Cannot find module './lib/filesystem.js'

### ISSUE THREAD

**Issue by joelQuispe** [file-icons/atom#769]
hola que tal acaba de actualizar fileIcon y al reiniciar atom me salio un error, quisiera saber si ya se toparon con este problema y como lo solucionaron

`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.25

### Stack Trace

Failed to activate the file-icons package

```
At Cannot find module './lib/filesystem.js'

Error: Cannot find module './lib/filesystem.js'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:154368)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/file-icons/node_modules/atom-fs/index.js:17:10)
    at /packages/file-icons/node_modules/atom-fs/index.js:23:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/file-icons/lib/storage.js:4:18)
    at /packages/file-icons/lib/storage.js:347:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/file-icons/lib/main.js:4:25)
    at Object.activate (/packages/file-icons/lib/main.js:11:8)
    at Package.activateNow (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:3033048)
    at measure (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:3032460)
    at Package.measure (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:3030091)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:3032320)
    at new Promise (<anonymous>)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-eclipse-syntax 0.0.6 
atom-monokai 0.10.9 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
autumn-highlighter-syntax 3.0.2 
base16-tomorrow-dark-theme-vivid 3.0.0 
base16-tomorrow-night-eighties-syntax 0.12.0 
burn 0.2.1 
city-lights-syntax 1.1.8 
color-picker 2.3.0 
cupcake-syntax 0.7.1 
docblockr 0.13.7 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.25 
highlight-line 0.12.0 
highlight-selected 0.14.0 
jackhammer-syntax 1.1.0 
minimap 4.29.9 
monokai 0.24.0 
monokai-dark 1.5.0 
neon-color-scheme 1.0.0 
now-syntax 0.2.4 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
raischburn-syntax 1.2.0 
spacegray-tomorrowdark-ui 2.1.0 
styri-syntax 1.0.0 
tomorrow-evening-syntax 1.1.0 
tomorrow-night-eighties-syntax 1.1.0 
vertex-ui 0.11.0 
```

`

**Comment by Alhadis** [comment]
I only speak English, I'm sorry. Hopefully these instructions are clear to you. =)

Some of the package files may not have downloaded correctly. To fix this:

1. Close all Atom windows
2. Delete the following directories:
	* `C:\Users\TU_NOMBRE\.atom\packages\file-icons`
	* `C:\Users\TU_NOMBRE\.atom\.apm`
3. Reopen Atom, then try to install `file-icons` again:
	* **Settings** → **Install…** → `"file-icons"`

I apologise for the slow response.

**Comment by Alhadis** [comment]
@carlosgonzalez Ayuda

**Comment by carlosgonzalez** [comment]
@joelQuispe 
Hola Joel, puedes probar los pasos que te puso @Alhadis 

1. Cerrar Atom completamente. Todas las ventadnas deben estar cerradas
2. Eliminar las siguientes carpetas:
- C:\Usuarios\NOMBRE_DE_USUARIO\.atom\packages\file-icons
- C:\Usuarios\NOMBRE_DE_USUARIO\.atom\.apm
3. Abrir Atom de nuevo y tratar de reinstalar file-icons
