### ISSUE TITLE
Uncaught TypeError: this.master.getCurrentIcon is not a function

### ISSUE THREAD

**Issue by brunobord** [file-icons/atom#771]
Steps to reproduce:

1. Open Atom
2. see an ugly error message

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Ubuntu 16.04.5
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.27

### Stack Trace

Uncaught TypeError: this.master.getCurrentIcon is not a function

```
At /home/user/.atom/packages/file-icons/lib/service/icon-delegate.js:76

TypeError: this.master.getCurrentIcon is not a function
    at IconDelegate.getClasses (/packages/file-icons/lib/service/icon-delegate.js:76:18)
    at IconNode.refresh (/packages/file-icons/lib/service/icon-node.js:79:39)
    at IconNode.disposables.add.delegate.onDidChangeIcon (/packages/file-icons/lib/service/icon-node.js:33:40)
    at Function.simpleDispatch (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1189948)
    at Emitter.emit (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1191389)
    at IconDelegate.emitIconChange (/packages/file-icons/lib/service/icon-delegate.js:61:17)
    at IconDelegate.set (/packages/file-icons/lib/service/icon-delegate.js:318:12)
    at to.onDidChangeMaster.to (/packages/file-icons/lib/service/icon-delegate.js:307:48)
    at Function.simpleDispatch (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1189948)
    at Emitter.emit (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1191389)
    at IconDelegate.set (/packages/file-icons/lib/service/icon-delegate.js:315:21)
    at /packages/file-icons/lib/service/icon-delegate.js:324:15)
    at disposables.add.resource.onDidChangeRealPath (/packages/file-icons/lib/service/icon-service.js:73:18)
    at Function.simpleDispatch (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1189948)
    at Emitter.emit (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1191389)
    at Directory.emit (/packages/file-icons/node_modules/atom-fs/lib/resource.js:100:17)
    at Immediate.setImmediate (/packages/file-icons/node_modules/atom-fs/lib/resource.js:260:28)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
blackboard-bb-ui 0.3.0 
busy-signal 2.0.0 
editorconfig 2.2.2 
file-icons 2.1.27 
file-watcher 2.0.0 
intentions 1.1.5 
jslint 1.5.1 
language-dot 1.7.0 
language-ini 1.20.0 
language-restructuredtext 1.1.2 
linter 2.2.0 
linter-flake8 2.3.0 
linter-markdown 5.2.2 
linter-ui-default 1.7.1 
markdown-lists 0.0.2 
markdown-mindmap 0.6.1 
markdown-table-formatter 2.9.2 
pretty-json 2.0.3 
sort-lines 0.18.0 
teletype 0.13.3 
```

**Comment by Alhadis** [comment]
Ouch. That's rare to see at startup. :| The stack trace indicates it was a race condition triggered by the target of a symbolic link being deleted/removed shortly before the symlink's target could be resolved.

Do you have any build scripts or filesystem watchers active in the workspace that may have caused this?
