### ISSUE TITLE
Failed to activate the file-icons package:Cannot find module 'atom-fs'

### ISSUE THREAD

**Issue by VWWVVW** [file-icons/atom#775]
**Atom**: 1.34.0 x64
**Electron**: 3.1.1
**OS**: linux 4.20.5-arch1-1-ARCH
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.29

### Stack Trace

Failed to activate the file-icons package

```
At Cannot find module 'atom-fs'

Error: Cannot find module 'atom-fs'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:283:28)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/file-icons/lib/storage.js:4:18)
    at /packages/file-icons/lib/storage.js:347:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/file-icons/lib/main.js:4:25)
    at Object.activate (/packages/file-icons/lib/main.js:11:8)
    at Package.activateNow (/usr/lib/atom/src/package.js:224:27)
    at measure (/usr/lib/atom/src/package.js:200:27)
    at Package.measure (/usr/lib/atom/src/package.js:82:19)
    at activationPromise.Promise (/usr/lib/atom/src/package.js:194:14)
    at new Promise (<anonymous>)
    at Package.activate (/usr/lib/atom/src/package.js:192:32)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:702:36)
    at config.transactAsync (/usr/lib/atom/src/package-manager.js:677:30)
    at Config.transactAsync (/usr/lib/atom/src/config.js:852:22)
    at PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:675:17)
    at PackageManager.activate (/usr/lib/atom/src/package-manager.js:654:44)
    at loadStatePromise.loadState.then (/usr/lib/atom/src/atom-environment.js:847:21)
```

### Non-Core Packages

```
file-icons 2.1.29 
```

### More Information
I didn't install this package by clicking the Install Button from the Setting page in atom because of the [GFW](https://en.wikipedia.org/wiki/Great_Firewall). Instead, I downloaded the source code to ~/.atom/package/ and used command *apm install* to install it.
I also find this error similar to #769. I wonder if there's a way to install this package manually.
Sorry for taking your time.

**Comment by VWWVVW** [comment]
Yes, it now works perfectly on my computer. This error results from not using *apm install* in a right directory.
I also find that it displays *Installing modules ✓* after I use *apm install* in any directories. When it comes to *npm install*, it displays errors if I don't use it in *~/.atom/packages/file-icons*.
Thank you.

**Comment by sbrl** [comment]
Just run into this issue randomly, and the above solution did _not_ work for me:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0-beta0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.10
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.46


### Stack Trace

Failed to activate the file-icons package

```
At Cannot mix BigInt and other types, use explicit conversions

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at BigIntStats._checkModeProperty (internal/fs/utils.js:364:21)
    at BigIntStats.StatsBase.isDirectory (internal/fs/utils.js:287:15)
    at FileSystem.resolveType (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:110:28)
    at FileSystem.get (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:69:13)
    at /packages/file-icons/lib/ui.js:34:29
    at Function.simpleDispatch (/usr/share/atom-beta/resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (/usr/share/atom-beta/resources/app/static/<embedded>:11:1184151)
    at /packages/file-icons/lib/ui.js:61:19
    at Workspace.observeTextEditors (/usr/share/atom-beta/resources/app/static/<embedded>:11:430973)
    at UI.observe (/packages/file-icons/lib/ui.js:56:19)
    at Object.activate (/packages/file-icons/lib/main.js:14:11)
    at Package.activateNow (/usr/share/atom-beta/resources/app/static/<embedded>:11:3366098)
    at /usr/share/atom-beta/resources/app/static/<embedded>:11:3365510
    at Package.measure (/usr/share/atom-beta/resources/app/static/<embedded>:11:3363088)
    at /usr/share/atom-beta/resources/app/static/<embedded>:11:3365370
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom-beta/resources/app/static/<embedded>:11:3365313)
    at PackageManager.activatePackage (/usr/share/atom-beta/resources/app/static/<embedded>:11:385022)
    at /usr/share/atom-beta/resources/app/static/<embedded>:11:384638
    at Config.transactAsync (/usr/share/atom-beta/resources/app/static/<embedded>:11:334166)
    at PackageManager.activatePackages (/usr/share/atom-beta/resources/app/static/<embedded>:11:384588)
    at PackageManager.activate (/usr/share/atom-beta/resources/app/static/<embedded>:11:384138)
    at /usr/share/atom-beta/resources/app/static/<embedded>:1:778467
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/usr/share/atom-beta/resources/app/static/<embedded>:1:778952)
```

### Commands

```
     -0:01.9.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-ide-debugger-native-gdb 0.7.3 
atom-ide-debugger-node 0.7.3 
atom-ide-ui 0.13.0 
atom-linter-phpstan 2.1.1 
atom-ternjs 0.20.0 
atom-typescript 14.1.2 
audio 1.5.7 
aural-coding 1.0.1 
autocomplete-awk 0.1.2 
autocomplete-clang 0.13.1 
autocomplete-glsl 0.2.3 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.5 
autocomplete-lua 0.9.2 
autocomplete-math 0.1.1 
autocomplete-modules 2.3.0 
autocomplete-paths 2.13.0 
autocomplete-sql 0.5.0 
bibtex-helper 2.0.0 
busy 0.7.0 
busy-signal 2.0.1 
caniuse 1.0.0 
change-case 0.6.5 
close-tags 0.6.0 
color-picker 2.3.0 
column-select 1.0.1 
css-hyperclick 0.1.5 
cursor-history 0.14.0 
devdocs 0.2.1 
docblockr 0.13.7 
document-outline 2.1.2 
file-icons 2.1.46 
font-preview 0.1.2 
git-log 0.4.1 
github-user-datatip 0.3.2 
highlight-selected 0.17.0 
hyperclick 0.0.0 
hyperclick-latex 0.5.8 
hyperclick-markdown 0.2.2 
hyperlink-hyperclick 3.0.2 
ide-bash 1.0.11 
ide-cpp 0.1.0 
ide-csharp 0.6.2 
ide-css 0.3.5 
ide-docker 0.1.0 
ide-html 0.6.2 
ide-json 0.2.1 
ide-python 1.7.4 
ide-rust 0.22.0-beta.3 
ide-typescript 0.9.1 
inline-markdown-images 1.15.0 
intentions 1.1.5 
js-hyperclick 1.19.0 
language-arduino 0.4.3 
language-awk 0.1.12 
language-bison-improved 0.9.7 
language-bnf 1.1.0 
language-cshtml 0.4.2 
language-diff 0.7.0 
language-docker 1.1.8 
language-gitignore 0.3.0 
language-glsl 2.0.4 
language-gnuplot-atom 0.2.0 
language-hcl 0.4.0 
language-hjson 1.0.2 
language-ignore 1.8.0 
language-ilasm 0.0.1 
language-ini 1.23.0 
language-latex 1.2.0 
language-lex-flex-new 0.2.1 
language-lua 0.9.11 
language-markdown 0.37.0 
language-nginx 0.8.0 
language-openscad 0.4.3 
language-prolog 0.11.0 
language-regexp 1.1.3 
language-rust 0.4.12 
language-svg 0.9.2 
latex-completions 0.3.6 
latex-hyperclick 0.2.0 
line-count-status 0.0.3 
linter 3.3.0 
linter-flake8 2.4.0 
linter-gcc 0.9.0 
linter-jsonlint 1.4.0 
linter-lua 2.0.0 
linter-php 1.6.1 
linter-rust-cargo 1.1.0 
linter-shellcheck 1.6.0 
linter-tidy 2.4.0 
linter-toml 0.1.1 
linter-ui-default 3.3.0 
MagicPython 1.1.1 
minimap 4.39.9 
minimap-bookmarks 0.4.6 
minimap-codeglance 0.4.7 
minimap-find-and-replace 5.0.8 
minimap-git-diff 4.3.6 
minimap-highlight-selected 4.6.5 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
minimap-selection 4.5.4 
minimap-titles 1.15.0 
move-status-items 0.1.1 
nearley-grammar 0.1.3 
open-in-browser 0.5.2 
package-cop 0.2.10 
pdf-view 0.72.0 
php-debug 0.3.5 
php-ide-serenata 5.4.0 
pigments 0.40.6 
project-manager 3.3.8 
project-plus 1.0.0 
protector 0.2.3 
rainbow-csv 1.4.0 
rainbow-tabs 2.5.1 
rainbow-tabs-evolved 2.7.13 
regex-railroad-diagram 0.19.4 
spell-check-urls 0.4.1 
ssh-config 0.14.0 
Sublime-Style-Column-Selection 1.7.5 
summer-night-syntax 2.0.1 
switch-header-source 0.34.5 
sync-settings 5.2.7 
teletype 0.13.4 
terminal-tab 0.6.0 
wordcount 3.2.0 
Zen 0.18.0 
```
