### ISSUE TITLE
Uncaught Error: ENXIO: no such device or address, read

### ISSUE THREAD

**Issue by gaboogled** [file-icons/atom#782]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.31

### Stack Trace

Uncaught Error: ENXIO: no such device or address, read

```
At fs.js:675

Error: ENXIO: no such device or address, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:575:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at File.loadData (/packages/file-icons/node_modules/atom-fs/lib/file.js:63:10)
    at LinguistStrategy.registerResource (/packages/file-icons/lib/service/strategies/linguist-strategy.js:86:12)
    at LinguistStrategy.check (/packages/file-icons/lib/service/strategy.js:133:9)
    at StrategyManager.query (/packages/file-icons/lib/service/strategy-manager.js:85:32)
    at Immediate.setImmediate (/packages/file-icons/lib/service/icon-delegate.js:245:38)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
file-icons 2.1.31 
git-plus 8.6.2 
git-plus-toolbar 1.0.1 
Hydrogen 2.8.0 
ide-php 0.7.18 
jekyll 2.1.0 
php-cs-fixer 4.1.1 
php-debug 0.3.5 
php-tools 0.1.0 
php-unit-integrator 0.0.56 
preview-plus 1.2.7 
shared-settings 0.0.6 
teletype 0.13.3 
tool-bar 1.1.11 
```

**Comment by Alhadis** [comment]
What were you doing when you saw this message? Accessing something through a remote file share? Or just browsing files locally on your own hard drive?

**Comment by Alhadis** [comment]
No response from submitter; closing.

If you can reproduce this error with more information, please post a comment letting me know.
