### ISSUE TITLE
Failed to activate file-icons: entity.addEditor is not a function

### ISSUE THREAD

**Issue by Datseris** [file-icons/atom#786]
1. Delete temporary files of your operating system (**I don't know if this is related**)
2. Try to install the package
3. Get the error.

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.32

### Stack Trace

Failed to activate the file-icons package

```
At entity.addEditor is not a function

TypeError: entity.addEditor is not a function
    at disposables.add.onOpenFile.editor (/packages/file-icons/lib/ui.js:39:22)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:1172164)
    at Emitter.emit (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:1173605)
    at disposables.add.atom.workspace.observeTextEditors.editor (/packages/file-icons/lib/ui.js:60:19)
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:428374)
    at UI.observe (/packages/file-icons/lib/ui.js:55:19)
    at Object.activate (/packages/file-icons/lib/main.js:14:11)
    at Package.activateNow (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3175323)
    at measure (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3174735)
    at Package.measure (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3172366)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3174595)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3174538)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:382705)
    at ~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:899155
    at r (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:893761)
    at o (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:1032937)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:1033143)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.32 
highlight-selected 0.16.0 
indent-detective 0.3.2 
ink 0.10.5 
julia-client 0.8.3 
language-julia 0.18.1 
language-latex 1.2.0 
latex-completions 0.3.6 
markdown-preview-plus 3.8.1 
pdf-view 0.71.0 
tibber 0.3.0 
toggle-quotes 1.1.4 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by Alhadis** [comment]
> 1. Delete temporary files of your operating system

When you say *"temporary files"*, which files are you referring to, exactly?

**Comment by Datseris** [comment]
The files in AppData/Local/Temp. This foldrr became too large for me and I had to nuke it.

**Comment by Datseris** [comment]
Everything else in atom is working fine.

**Comment by Datseris** [comment]
It works now.
