### ISSUE TITLE
Install fails (maximum callstack exceeded)

### ISSUE THREAD

**Issue by nerdyman** [file-icons/atom#788]
Hi,

I previously had file-icons installed but the package broke when trying to upgrade to  `file-icons@2.1.35`, removing/reinstalling doesn't fix the issue.

This is the output from `apm install file-icons`

```
Installing file-icons to /home/me/.atom/packages /usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:194
    if (this instanceof ReadStream)
             ^

RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at ReadStream (/usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:194:14)
    at ReadStream (/usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:195:28)
    at ReadStream (/usr/lib/node_modules/atom-package-manager/node_modules/graceful-fs/graceful-fs.js:195:28)
```

I'm using Node `11.15.0`.

**Comment by Alhadis** [comment]
This seems to be an upstream issue with [Atom's package manager](https://github.com/atom/apm), which occasionally barfs under certain network condition.

Your best bet is to file a report there, as this issue really isn't something we have any control over.

**Comment by nerdyman** [comment]
OK cool I'll take a look at the APM issues, thanks for the quick response!

**Comment by gavsiu** [comment]
I had this exact issue when I was using Atom 1.39.1. The issue is gone with 1.40.1.

**Comment by Alhadis** [comment]
Definitely an upstream issue, or something related to your environment. Heck, I don't think there have even been any package updates between those two releases...

**Comment by gavsiu** [comment]
If it makes a difference, I had the atom 1.39.1-1 package in the Arch Linux Community repo installed. I uninstalled it and installed atom-editor-bin 1.40.1-1 from AUR.

**Comment by Alhadis** [comment]
There's no official port of Atom for Arch Linux, meaning that what you were using is maintained by the community, rather than the Atom team.

So if the problem appears to be with that build, I'd suggest bringing it up with the users maintaining the port. 😉

**Comment by nerdyman** [comment]
Yep, my bad, I'm using Arch too. Arch's Atom has been flagged as out of date https://www.archlinux.org/packages/community/x86_64/atom/.
