### ISSUE TITLE
Uncaught TypeError: pattern.indexOf is not a function

### ISSUE THREAD

**Issue by jonbackhaus** [file-icons/atom#790]
[Enter steps to reproduce:]

1. Updated `config.cson` to include the following: 
```
"*":
  core:
    customFileTypes:
      "source.ansible-advanced": [
        {
          ".*.yml$": "source.ansible-advanced"
          ".*/group_vars/.*": "source.ansible-advanced"
          ".*/host_vars/.*": "source.ansible-advanced"
        }
      ]
```

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.35

### Stack Trace

Uncaught TypeError: pattern.indexOf is not a function

```
At /Users/jbackhau/.atom/packages/file-icons/lib/service/strategies/usertype-strategy.js:90

TypeError: pattern.indexOf is not a function
    at UsertypeStrategy.updateCustomTypes (/packages/file-icons/lib/service/strategies/usertype-strategy.js:90:21)
    at configDisposable.atom.config.onDidChange.types (/packages/file-icons/lib/service/strategies/usertype-strategy.js:36:11)
    at emitter.on (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334486)
    at Function.simpleDispatch (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at Config.emitChangeEvent (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:336974)
    at Config.endTransaction (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:331745)
    at Config.transact (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:331364)
    at Config._resetSettings (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332997)
    at Config.resetUserSettings (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332764)
    at disposables.add.applicationDelegate.onDidChangeUserSettings.e (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:707939)
    at ipcMessageEmitter.on.t (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725190)
    at Function.simpleDispatch (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at EventEmitter._ipcMessageEmitter.get_ipcRenderer.on (/Users/jbackhau/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:721840)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -0:10.8.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:10.4.0 core:select-left (input.hidden-input)
     -0:09.7.0 core:copy (input.hidden-input)
     -0:09.5.0 core:move-down (input.hidden-input)
  4x -0:08.9.0 core:move-right (input.hidden-input)
     -0:07.7.0 core:paste (input.hidden-input)
     -0:07.4.0 core:move-down (input.hidden-input)
     -0:07.2.0 core:move-right (input.hidden-input)
     -0:06.9.0 core:move-left (input.hidden-input)
     -0:06.6.0 core:paste (input.hidden-input)
     -0:06.4.0 core:move-down (input.hidden-input)
     -0:06.3.0 core:move-left (input.hidden-input)
     -0:06.0 core:paste (input.hidden-input)
     -0:05.3.0 core:move-down (input.hidden-input)
     -0:04.8.0 core:move-up (input.hidden-input)
     -0:04.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
autocomplete-ansible 0.1.24 
busy-signal 2.0.1 
file-icons 2.1.35 
file-types 1.0.1 
gitlab 0.1.3-7 
intentions 1.1.5 
language-ansible 0.2.2 
language-confluence-wiki 0.2.0 
language-markdown 0.37.0 
linter 2.3.1 
linter-ansible-linting 1.5.0 
linter-markdown 5.2.9 
linter-ui-default 1.8.0 
markdown-document 0.2.1 
markdown-pdf 2.2.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.11.7 
platformio-ide-terminal 2.9.4 
prettier-atom 0.57.2 
sort-lines 0.19.0 
structure-view 0.2.1 
switch-quotes 0.1.0 
xpath 0.2.1-0 
```

**Comment by jonbackhaus** [comment]
Resolved: user error in entering configuration.
