### ISSUE TITLE
Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions

### ISSUE THREAD

**Issue by claytonrcarter** [file-icons/atom#842]
1. I just updated Atom Beta from 1.55 to 1.56
2. Started seeing this error @ launch, though it's attributed to `tree-view` initial. Closing that dialog and trying to open a directory in tree view then triggers this error. 
3. Close atom, run `apm-beta remove file-icons`
4. Launch Atom Beta: no error generated
5. Close atom, run `apm-beta install file-icons`
6. Launch Atom Beta: error generated again.

Happy to provide more info if needed.

**Atom**: 1.56.0-beta0 x64
**Electron**: 9.4.4
**OS**: macOS 11.2.2
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.46

### Stack Trace

Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions

```
At internal/fs/utils.js:364

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at BigIntStats._checkModeProperty (internal/fs/utils.js:364:21)
    at BigIntStats.StatsBase.isDirectory (internal/fs/utils.js:287:15)
    at FileSystem.resolveType (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:110:28)
    at FileSystem.get (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:69:13)
    at Object.iconClassForPath (/packages/file-icons/lib/service/icon-service.js:101:29)
    at IconServices.updateFileIcon (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:972675)
    at FileView.updateIcon (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:3406183)
    at new FileView (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:3405993)
    at DirectoryView.createViewForEntry (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2771730)
    at /Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2771420
    at Function.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:1184151)
    at Directory.reload (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2767480)
    at Directory.expand (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2767700)
    at DirectoryView.expand (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2772195)
    at DirectoryView.toggleExpansion (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2771982)
    at TreeView.entryClicked (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:985621)
    at HTMLDivElement.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:980068)
```

### Commands

```
     -0:07.1.0 typescript:activate (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
expand-region 0.5.0 
atom-handlebars 1.3.0 
atom-ide-base 2.3.5 
atom-ide-datatip 0.24.0 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.9 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.0.0 
atom-ide-outline 2.0.0 
atom-ide-signature-help 0.15.3 
atom-ide-vue 1.4.5 
atom-linter-phpstan 2.1.1 
atom-phpunit 1.3.0 
atom-typescript 14.1.2 
autocomplete-paths 2.13.0 
blade-snippets 0.2.0 
block-travel 1.0.7 
busy-signal 2.0.1 
calc 0.4.0 
center-line 1.4.0 
change-case 0.6.5 
clipboard-plus 0.5.1 
docblockr 0.13.7 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.46 
firefox-syntax 4.2.0 
git-blame 1.8.0 
git-tab-status 1.9.2 
go-plus 6.1.0 
highlight-selected 0.17.0 
hyperclick-php 0.3.0 
ide-css 0.3.5 
ide-go 0.12.3 
ide-php 0.7.18 
ide-typescript 0.9.1 
intentions 1.1.5 
javascript-drag-import 0.1.13 
js-hyperclick 1.13.3 
jumpy 5.0.2 
keyboard-scroll 0.7.0 
language-awk 0.1.12 
language-blade 0.46.0 
language-docker 1.1.8 
language-dotenv 1.2.0 
language-htaccess 0.2.0 
language-markdown 0.37.0 
language-vue 0.26.0 
line-diff-details-plus 1.9.1 
linter 3.3.0 
linter-eslint 8.5.5 
linter-php 1.6.1 
linter-phpcs 1.7.6 
linter-phpmd 2.0.2 
linter-ui-default 3.3.0 
magic-reflow 0.3.0 
minimap 4.39.9 
minimap-find-and-replace 5.0.8 
minimap-git-diff 4.3.6 
minimap-highlight-selected 4.6.5 
minimap-selection 4.5.4 
multi-paste 0.3.1 
pain-split 1.4.0 
php-cs-fixer 4.2.0 
php-ide-serenata 5.4.0 
php-twig 4.0.0 
prettier-atom 0.60.1 
project-manager 3.3.8 
remember-file-positions 0.2.3 
remember-folds 0.3.0 
semanticolor 3.7.0 
Sublime-Style-Column-Selection 1.7.5 
terminal-commands 1.4.0 
x-terminal 13.0.1 
zap-to-char 0.1.1 
```

**Comment by claytonrcarter** [comment]
Oops, just did some more digging and I see that this is already reported at atom-fa: https://github.com/file-icons/atom-fs/issues/10
