### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by hcsimbanac** [file-icons/atom#846]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.47

### Stack Trace

Failed to activate the file-icons package

```
At Cannot find module 'atom-fs'
Require stack:
- C:\Users\Helen\.atom\packages\file-icons\lib\storage.js
- C:\Users\Helen\.atom\packages\file-icons\lib\main.js
- C:\Users\Helen\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html

Error: Cannot find module 'atom-fs'
Require stack:
- C:\Users\Helen\.atom\packages\file-icons\lib\storage.js
- C:\Users\Helen\.atom\packages\file-icons\lib\main.js
- C:\Users\Helen\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/file-icons/lib/storage.js:4:18)
    at /packages/file-icons/lib/storage.js:346:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/file-icons/lib/main.js:4:25)
    at Object.activate (/packages/file-icons/lib/main.js:11:8)
    at Package.activateNow (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3497376)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3496788
    at Package.measure (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3494366)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3496648
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3496591)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:383646)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:383262
    at Config.transactAsync (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:332808)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:383212)
    at PackageManager.activate (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:382762)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:1:758818
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:1:759303)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.47 
minimap 4.39.10 
```

**Comment by Alhadis** [comment]
1. Abra <ins>atom://config/packages/file-icons</ins>
2. Buscar `file-icons`
3. Haga clic en <img src="https://user-images.githubusercontent.com/2346707/112703235-3f465f00-8eea-11eb-929f-05155cfe6f69.png" width="73" alt="Install" valign="bottom" />
4. Ya esta
