### ISSUE TITLE
Failed to activate the file-icons package

### ISSUE THREAD

**Issue by SwitchArio** [file-icons/atom#848]
Just run into this issue randomly, and [this](https://github.com/file-icons/atom/issues/775) solution did not work for me:

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.46

### Stack Trace

Failed to activate the file-icons package

```
At Cannot mix BigInt and other types, use explicit conversions

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at BigIntStats._checkModeProperty (internal/fs/utils.js:364:21)
    at BigIntStats.StatsBase.isDirectory (internal/fs/utils.js:287:15)
    at FileSystem.resolveType (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:110:28)
    at FileSystem.get (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:69:13)
    at /packages/file-icons/lib/ui.js:34:29
    at Function.simpleDispatch (<embedded>:11:1182710)
    at Emitter.emit (<embedded>:11:1184151)
    at /packages/file-icons/lib/ui.js:61:19
    at Workspace.observeTextEditors (<embedded>:11:430973)
    at UI.observe (/packages/file-icons/lib/ui.js:56:19)
    at Object.activate (/packages/file-icons/lib/main.js:14:11)
    at Package.activateNow (<embedded>:11:3484958)
    at <embedded>:11:3484370
    at Package.measure (<embedded>:11:3481948)
    at <embedded>:11:3484230
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3484173)
    at PackageManager.activatePackage (<embedded>:11:385022)
    at <embedded>:11:384638
    at Config.transactAsync (<embedded>:11:334166)
    at PackageManager.activatePackages (<embedded>:11:384588)
    at PackageManager.activate (<embedded>:11:384138)
    at <embedded>:1:824962
    at Function.all (<anonymous>:null:null)
    at AtomEnvironment.startEditorWindow (<embedded>:1:825447)

```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.25.0 
atom-runner 2.7.1 
autocomplete-python 1.17.0 
file-icons 2.1.46 
highlight-selected 0.17.0 
language-vue 0.26.0 
minimap 4.39.8 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
python-tools 0.6.9 
```

**Comment by Alhadis** [comment]
> **Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.46

You're running an outdated version of `file-icons`. The issue you're reporting was fixed in [`v2.1.47`](https://github.com/file-icons/atom/releases/tag/v2.1.47).

Upgrade the package, and the problem will go away.
