### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by AshlyMcC** [file-icons/atom#872]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.6
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.47

### Stack Trace

Uncaught SyntaxError: Unexpected identifier

```
At /Users/thecurious/.atom/packages/file-icons/lib/storage.js:165

SyntaxError: Unexpected identifier
    at Storage.setPathID (/packages/file-icons/lib/storage.js:243:20)
    at IconService.handleResource (/packages/file-icons/lib/service/icon-service.js:65:12)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1189107)
    at FileSystem.get (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:94:17)
    at Function.forElement (/packages/file-icons/lib/service/icon-node.js:180:28)
    at /packages/file-icons/lib/service/icon-service.js:91:31)
    at IconServices.updateDirectoryIcon (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1031353)
    at DirectoryView.updateIcon (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2851245)
    at new DirectoryView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2849568)
    at DirectoryView.createViewForEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2851943)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2851654
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1189107)
    at Directory.reload (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2847714)
    at Directory.expand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2847934)
    at DirectoryView.expand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2852429)
    at DirectoryView.toggleExpansion (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2852216)
    at TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1044868)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1039315)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-increment 0.3.4 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-recover 0.1.0 
atom-sass 0.4.0 
build 0.70.0 
busy-signal 2.0.1 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.47 
highlight-selected 0.17.0 
intentions 2.1.1 
language-blade 0.46.0 
language-liquid 0.7.0 
language-mjml 2.1.0 
linter 3.4.0 
linter-eslint 8.6.6 
linter-mjml 1.2.0 
linter-ui-default 3.4.1 
material-ui 1.0.10 
minimap 4.40.0 
mjml-preview 2.0.3 
native-ui 0.27.0 
todo-show 2.3.2 
```

**Comment by Alhadis** [comment]
Was this a one-off case? Or has this happened multiple times?

Please provide some details so I have something more substantial to go off of when investigating this issue.
